// Generated from SDK response types. Do not edit by hand.
// Keep this in sync when a public response type or operation changes.
import type { SuccessContractData } from "./response-contract.js";

// biome-ignore format: Generated contract graph; one schema per line keeps changes reviewable.
export const successContractData: SuccessContractData = {
  "operations": {
    "GET /health": {"ref":0},
    "GET /liveness": {"ref":51},
    "GET /readiness": {"ref":52},
    "GET /openapi.json": {"ref":53},
    "GET /capabilities": {"ref":55},
    "GET /llms.txt": "string",
    "GET /provider-rates": {"ref":57},
    "GET /cost-estimate": {"ref":62},
    "GET /locations/search": {"ref":66},
    "GET /me": {"ref":69},
    "PATCH /me": {"ref":69},
    "GET /me/tokens": {"ref":71},
    "POST /me/tokens": {"ref":73},
    "DELETE /me/tokens/*": {"ref":72},
    "GET /projects": {"ref":74},
    "POST /projects": {"ref":75},
    "GET /projects/*": {"ref":75},
    "PATCH /projects/*": {"ref":75},
    "DELETE /projects/*": {"ref":75},
    "GET /projects/*/defaults": {"ref":76},
    "GET /projects/*/overview": {"ref":77},
    "POST /projects/*/keyword-matches": {"ref":79},
    "PATCH /projects/*/defaults": {"ref":76},
    "GET /api-keys": {"ref":83},
    "POST /api-keys": {"ref":85},
    "DELETE /api-keys/*": {"ref":84},
    "GET /projects/*/api-keys": {"ref":83},
    "POST /projects/*/api-keys": {"ref":85},
    "GET /projects/*/webhooks": {"ref":86},
    "POST /projects/*/webhooks": {"ref":87},
    "PATCH /projects/*/webhooks/*": {"ref":87},
    "DELETE /projects/*/webhooks/*": {"ref":87},
    "GET /projects/*/keywords": {"ref":88},
    "POST /projects/*/keywords": {"ref":91},
    "GET /keywords/*": {"ref":89},
    "PATCH /keywords/*": {"ref":89},
    "DELETE /keywords/*": {"ref":89},
    "POST /keywords/bulk": {"ref":93},
    "GET /projects/*/ranked-keyword-suggestions": {"ref":95},
    "GET /projects/*/keyword-research": {"oneOf":[{"ref":98},{"ref":101}]},
    "GET /projects/*/backlinks": {"ref":105},
    "POST /projects/*/backlinks/rows": {"ref":111},
    "POST /projects/*/domain-overview/analyze": {"ref":112},
    "POST /projects/*/domain-overview/history": {"ref":123},
    "POST /projects/*/domain-overview/keywords": {"ref":126},
    "POST /projects/*/domain-overview/pages": {"ref":128},
    "POST /projects/*/keyword-metrics": {"ref":130},
    "GET /projects/*/exports/rank-history": {"ref":132},
    "GET /projects/*/sitemap-monitors": {"ref":134},
    "PATCH /projects/*/sitemap-monitors/*": {"ref":135},
    "GET /keywords/*/rank-checks": {"ref":137},
    "POST /keywords/*/checks": {"oneOf":[{"ref":138},{"ref":140}]},
    "GET /rank-checks/*": {"ref":138},
    "POST /signals": {"ref":141},
    "GET /projects/*/signals": {"ref":142},
    "GET /projects/*/analytics/traffic-snapshots": {"ref":143},
    "GET /projects/*/analytics/query-stats": {"ref":145},
    "POST /projects/*/analytics/sync": {"ref":148},
    "GET /projects/*/alert-rules": {"ref":151},
    "POST /projects/*/alert-rules": {"oneOf":[{"ref":152},{"ref":153},{"ref":154}]},
    "PATCH /alert-rules/*": {"oneOf":[{"ref":152},{"ref":153},{"ref":154}]},
    "DELETE /alert-rules/*": {"ref":155},
    "GET /projects/*/triggered-alerts": {"ref":156},
    "POST /projects/*/triggered-alerts/*/mute": {"ref":158},
    "POST /projects/*/triggered-alerts/mark-read": {"ref":159},
    "GET /projects/*/team/members": {"ref":160},
    "GET /projects/*/team/invites": {"ref":162},
    "POST /projects/*/team/invites": {"ref":164},
    "DELETE /projects/*/team/invites/*": {"ref":165},
    "DELETE /team/invites/*": {"ref":165},
    "POST /projects/*/team/invites/*/resend": {"ref":166},
    "PATCH /projects/*/team/members/*": {"ref":167},
    "DELETE /projects/*/team/members/*": {"ref":168},
    "GET /projects/*/context": {"ref":169},
    "PATCH /projects/*/context": {"ref":169},
    "GET /projects/*/agent-reports": {"ref":171},
    "POST /projects/*/agent-reports": {"ref":173},
    "GET /projects/*/agent-reports/*": {"ref":173},
    "POST /projects/*/ai-visibility": {"ref":176},
    "POST /projects/*/prompt-explorer": {"ref":176},
    "GET /projects/*/site-audits": {"ref":182},
    "POST /projects/*/site-audits": {"ref":183},
    "GET /projects/*/site-audits/*": {"ref":183},
    "GET /projects/*/research/reports": {"ref":191},
    "GET /projects/*/research/reports/*": {"ref":194},
    "GET /projects/*/provider-budgets": {"ref":201},
    "PATCH /projects/*/providers/*/budgets": {"ref":202},
    "GET /projects/*/providers": {"ref":209},
    "POST /projects/*/providers/*/connect": {"ref":215},
    "POST /projects/*/providers/*/test": {"ref":216},
    "PATCH /projects/*/providers/*": {"ref":215},
    "DELETE /projects/*/providers/*": {"ref":217},
    "GET /projects/*/saved-views": {"ref":218},
    "POST /projects/*/saved-views": {"ref":219},
    "DELETE /projects/*/saved-views/*": {"ref":226},
    "DELETE /saved-views/*": {"ref":226},
    "GET /projects/*/saved-keywords": {"ref":227},
    "POST /projects/*/saved-keywords": {"ref":230},
    "DELETE /projects/*/saved-keywords/*": {"ref":232},
    "GET /projects/*/competitors": {"ref":233},
    "POST /projects/*/competitors": {"ref":241},
    "DELETE /projects/*/competitors/*": {"ref":242},
    "DELETE /competitors/*": {"ref":242},
    "GET /projects/*/notification-preferences": {"ref":243},
    "PATCH /projects/*/notification-preferences": {"ref":243},
    "GET /projects/*/migration-tokens": {"ref":244},
    "POST /projects/*/migration-tokens": {"ref":249},
    "DELETE /projects/*/migration-tokens/*": {"ref":250},
    "DELETE /migration-tokens/*": {"ref":250},
    "GET /cloud/import/compatibility": {"ref":251},
    "POST /cloud/import": {"ref":252},
    "POST /cloud/import/sessions": {"ref":254},
    "PUT /cloud/import/sessions/*/chunks/*": {"ref":256},
    "POST /cloud/import/sessions/*/finalize": {"ref":252}
  },
  "nodes": [
    {"object":{"status":{"oneOf":[{"ref":1},{"literal":"degraded"},{"literal":"ok"}]}}},
    {"object":{"toString":{"ref":2},"charAt":{"ref":3},"charCodeAt":{"ref":4},"concat":{"ref":5},"indexOf":{"ref":6},"lastIndexOf":{"ref":7},"localeCompare":{"ref":8},"match":{"ref":9},"replace":{"ref":10},"search":{"ref":11},"slice":{"ref":12},"split":{"ref":13},"substring":{"ref":14},"toLowerCase":{"ref":15},"toLocaleLowerCase":{"ref":16},"toUpperCase":{"ref":17},"toLocaleUpperCase":{"ref":18},"trim":{"ref":19},"length":"number","substr":{"ref":20},"valueOf":{"ref":21},"codePointAt":{"ref":22},"includes":{"ref":23},"endsWith":{"ref":24},"normalize":{"ref":25},"repeat":{"ref":26},"startsWith":{"ref":27},"anchor":{"ref":28},"big":{"ref":29},"blink":{"ref":30},"bold":{"ref":31},"fixed":{"ref":32},"fontcolor":{"ref":33},"fontsize":{"ref":34},"italics":{"ref":35},"link":{"ref":36},"small":{"ref":37},"strike":{"ref":38},"sub":{"ref":39},"sup":{"ref":40},"padStart":{"ref":41},"padEnd":{"ref":42},"trimEnd":{"ref":43},"trimStart":{"ref":44},"trimLeft":{"ref":45},"trimRight":{"ref":46},"matchAll":{"ref":47},"replaceAll":{"ref":48},"at":{"ref":49},"__@iterator@20":{"ref":50}}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{"status":{"oneOf":[{"ref":1},{"literal":"ok"}]}}},
    {"object":{"status":{"oneOf":[{"ref":1},{"literal":"degraded"},{"literal":"ok"}]}}},
    {"object":{"info":{"ref":54},"openapi":"string","paths":{"ref":54}}},
    {"object":{}},
    {"object":{"data":{"array":{"ref":56}}},"optional":{"apiVersions":{"array":"string"},"meta":{"ref":54}}},
    {"object":{"description":"string","input_schema":{"ref":54},"name":"string","operationId":"string"}},
    {"object":{"data":{"array":{"oneOf":[{"ref":58},{"ref":60}]}}},"optional":{"meta":{"ref":54}}},
    {"object":{"options":{"array":{"ref":59}},"pricing_model":{"literal":"flat"},"checked_at":"string","label":"string","provider_id":"string","source_url":"string"},"optional":{"notes":"string"}},
    {"object":{"key":"string","label":"string","short_label":"string","turnaround":"string","unit_cost_cents":"number","unit_cost_usd":"number"}},
    {"object":{"plans":{"array":{"ref":61}},"pricing_model":{"literal":"plan"},"checked_at":"string","label":"string","provider_id":"string","source_url":"string"},"optional":{"notes":"string"}},
    {"object":{"included_checks":"number","label":"string","monthly_price_cents":"number","monthly_price_usd":"number","plan_key":"string"}},
    {"object":{"data":{"oneOf":[{"ref":63},{"ref":65}]}},"optional":{"meta":{"ref":54}}},
    {"object":{"pricing_model":{"literal":"flat"},"selected_option":{"ref":64},"billing_units_per_check":"number","checks_per_run":"number","depth":{"oneOf":[{"literal":10},{"literal":20},{"literal":50},{"literal":100}]},"effective_cost_per_check_cents":{"oneOf":["null","number"]},"exceeds_largest_plan":"boolean","exceeds_selected_plan":"boolean","monthly_billing_units":{"oneOf":["null","number"]},"monthly_checks":{"oneOf":["null","number"]},"monthly_cost_cents":{"oneOf":["null","number"]},"monthly_cost_usd":{"oneOf":["null","number"]},"provider_id":"string","rate_checked_at":"string","rate_source_url":"string","result_pages_per_run":"number","runs_per_month":{"oneOf":["null","number"]}}},
    {"object":{"key":"string","label":"string","short_label":"string","turnaround":"string","unit_cost_cents":"number","unit_cost_usd":"number","additional_page_cost_cents":"number","additional_page_cost_usd":"number","top_100_check_cost_cents":"number","top_100_check_cost_usd":"number"}},
    {"object":{"pricing_model":{"literal":"plan"},"billing_units_per_check":"number","checks_per_run":"number","depth":{"oneOf":[{"literal":10},{"literal":20},{"literal":50},{"literal":100}]},"effective_cost_per_check_cents":{"oneOf":["null","number"]},"exceeds_largest_plan":"boolean","exceeds_selected_plan":"boolean","monthly_billing_units":{"oneOf":["null","number"]},"monthly_checks":{"oneOf":["null","number"]},"monthly_cost_cents":{"oneOf":["null","number"]},"monthly_cost_usd":{"oneOf":["null","number"]},"provider_id":"string","rate_checked_at":"string","rate_source_url":"string","result_pages_per_run":"number","runs_per_month":{"oneOf":["null","number"]}},"optional":{"selected_plan":{"ref":61}}},
    {"object":{"data":{"array":{"ref":67}},"meta":{"ref":68}}},
    {"object":{"city_name":{"oneOf":["null","string"]},"country_code":"string","display_name":"string","hl":"string","kind":{"oneOf":[{"literal":"city"},{"literal":"country"},{"literal":"region"}]},"language_code":"string","language_label":"string","location_key":"string","region_code":{"oneOf":["null","string"]},"region_name":{"oneOf":["null","string"]}}},
    {"object":{"next_cursor":{"oneOf":["null","string"]}}},
    {"object":{"email":"string","id":"string","name":"string","projects":{"array":{"ref":70}}}},
    {"object":{"domain":"string","id":"string","name":"string","role":{"oneOf":[{"literal":"admin"},{"literal":"auditor"},{"literal":"member"},{"literal":"owner"},{"literal":"viewer"}]}}},
    {"object":{"data":{"array":{"ref":72}},"meta":{"ref":68}}},
    {"object":{"created_at":"string","expires_at":{"oneOf":["null","string"]},"id":"string","last_used_at":{"oneOf":["null","string"]},"name":"string","prefix":"string","revoked_at":{"oneOf":["null","string"]},"scope":{"oneOf":[{"literal":"admin"},{"literal":"read"},{"literal":"write"}]}}},
    {"object":{"masked_value":"string","token":"string","created_at":"string","expires_at":{"oneOf":["null","string"]},"id":"string","last_used_at":{"oneOf":["null","string"]},"name":"string","prefix":"string","revoked_at":{"oneOf":["null","string"]},"scope":{"oneOf":[{"literal":"admin"},{"literal":"read"},{"literal":"write"}]}}},
    {"object":{"data":{"array":{"ref":75}},"meta":{"ref":68}}},
    {"object":{"created_at":"string","domain":"string","id":"string","name":"string","updated_at":"string","write_mode":{"oneOf":[{"literal":"active"},{"literal":"migration_hold"},{"literal":"migrated"}]}}},
    {"object":{"city":{"oneOf":["null","string"]},"country":"string","cron_expression":{"oneOf":["null","string"]},"device":{"oneOf":[{"literal":"desktop"},{"literal":"mobile"}]},"frequency":{"oneOf":[{"literal":"paused"},{"literal":"manual"},{"literal":"daily"},{"literal":"weekly"},{"literal":"monthly"},{"literal":"custom_cron"}]},"jitter_minutes":"number","last_checked_at":{"oneOf":["null","string"]},"location_key":"string","next_check_at":{"oneOf":["null","string"]},"project_id":"string","serp_depth":{"oneOf":[{"literal":10},{"literal":20},{"literal":50},{"literal":100}]},"serp_stop_on_match":"boolean","source":{"oneOf":[{"literal":"derived"},{"literal":"explicit"},{"literal":"fallback"}]},"timezone":"string","updated_at":{"oneOf":["null","string"]}}},
    {"object":{"average_position":{"oneOf":["null","number"]},"average_position_delta":{"oneOf":["null","number"]},"keywords_added_this_month":"number","last_check_at":{"oneOf":["null","string"]},"next_check_at":{"oneOf":["null","string"]},"position_distribution":{"array":{"ref":78}},"project_id":"string","top_10_count":{"oneOf":["null","number"]},"top_10_delta":{"oneOf":["null","number"]},"top_100_count":{"oneOf":["null","number"]},"top_3_count":{"oneOf":["null","number"]},"tracked_keyword_count":"number","visibility":{"oneOf":["null","number"]},"visibility_delta":{"oneOf":["null","number"]}}},
    {"object":{"count":{"oneOf":["null","number"]},"max":"number","min":"number"}},
    {"object":{"data":{"array":{"ref":80}},"meta":{"ref":82}}},
    {"object":{"keyword_id":"string","latest_position":{"oneOf":["null","number"]},"market":{"ref":81},"matched_text":"string","previous_position":{"oneOf":["null","number"]},"ranking_url":{"oneOf":["null","string"]},"text":"string"}},
    {"object":{"country_code":"string","device":{"oneOf":[{"literal":"desktop"},{"literal":"mobile"}]},"language_code":"string","language_label":"string","location":"string","location_key":"string"}},
    {"object":{"truncated_texts":{"array":"string"}}},
    {"object":{"data":{"array":{"ref":84}},"meta":{"ref":68}}},
    {"object":{"created_at":"string","expires_at":{"oneOf":["null","string"]},"id":"string","last_used_at":{"oneOf":["null","string"]},"name":"string","prefix":"string","revoked_at":{"oneOf":["null","string"]},"scope":{"oneOf":[{"literal":"admin"},{"literal":"read"},{"literal":"write"}]}}},
    {"object":{"masked_value":"string","token":"string","created_at":"string","expires_at":{"oneOf":["null","string"]},"id":"string","last_used_at":{"oneOf":["null","string"]},"name":"string","prefix":"string","revoked_at":{"oneOf":["null","string"]},"scope":{"oneOf":[{"literal":"admin"},{"literal":"read"},{"literal":"write"}]}}},
    {"object":{"data":{"array":{"ref":87}},"meta":{"ref":68}}},
    {"object":{"created_at":"string","description":{"oneOf":["null","string"]},"enabled":"boolean","id":"string","last_delivery_at":{"oneOf":["null","string"]},"updated_at":"string","url":"string"}},
    {"object":{"data":{"array":{"ref":89}},"meta":{"ref":68}}},
    {"object":{"country":"string","created_at":"string","device":{"oneOf":[{"literal":"desktop"},{"literal":"mobile"}]},"id":"string","intent":{"oneOf":["null","string"]},"language_code":"string","language_label":"string","latest_position":{"oneOf":["null","number"]},"location":"string","location_key":"string","previous_position":{"oneOf":["null","number"]},"project_id":"string","ranking_url":{"oneOf":["null","string"]},"schedule":{"oneOf":["null",{"ref":90}]},"tags":{"array":"string"},"target_url":{"oneOf":["null","string"]},"text":"string","topic":{"oneOf":["null","string"]},"updated_at":"string"}},
    {"object":{"cron_expression":{"oneOf":["null","string"]},"frequency":{"oneOf":[{"literal":"paused"},{"literal":"manual"},{"literal":"daily"},{"literal":"weekly"},{"literal":"monthly"},{"literal":"custom_cron"}]},"jitter_minutes":"number","last_checked_at":{"oneOf":["null","string"]},"next_check_at":{"oneOf":["null","string"]},"timezone":"string"}},
    {"object":{"created":"number","results":{"array":{"ref":92}},"skipped":"number"},"optional":{"warnings":{"array":"string"}}},
    {"object":{"keyword":{"ref":89},"status":{"oneOf":[{"ref":1},{"literal":"created"},{"literal":"skipped"}]}},"optional":{"warning":"string"}},
    {"object":{"operation":{"oneOf":[{"literal":"add_tags"},{"literal":"delete"},{"literal":"remove_tags"},{"literal":"set_frequency"},{"literal":"set_target_url"}]},"results":{"array":{"ref":94}}}},
    {"object":{"keyword_id":"string","status":{"oneOf":[{"ref":1},{"literal":"deleted"},{"literal":"not_found"},{"literal":"updated"}]}}},
    {"object":{"cached":"boolean","connections":{"array":{"ref":96}},"cost_cents":"number","fetched_at":"string","offset":"number","rows":{"array":{"ref":97}},"total_count":{"oneOf":["null","number"]}}},
    {"object":{"id":"string","label":"string","provider":{"literal":"dataforseo"}}},
    {"object":{"already_tracked":"boolean","estimated_traffic":{"oneOf":["null","number"]},"keyword":"string","position":{"oneOf":["null","number"]},"search_volume":{"oneOf":["null","number"]}}},
    {"object":{"cached":"boolean","connections":{"array":{"ref":99}},"cost_cents":"number","estimate":{"literal":true},"provider":"string","sources":{"array":{"ref":100}}}},
    {"object":{"id":"string","label":"string","provider":"string"}},
    {"object":{"cached":"boolean","cost_cents":"number","source":{"oneOf":[{"literal":"related"},{"literal":"suggestion"},{"literal":"idea"}]}}},
    {"object":{"cached":"boolean","connections":{"array":{"ref":99}},"cost_cents":"number","fetched_at":"string","provider":"string","rows":{"array":{"ref":102}},"sources":{"array":{"ref":104}},"total_count":"number"},"optional":{"estimate":"unknown"}},
    {"object":{"already_tracked":"boolean","source":{"oneOf":[{"literal":"related"},{"literal":"suggestion"},{"literal":"idea"}]},"keyword":"string","competition":{"oneOf":["null","number"]},"cpc_cents":{"oneOf":["null","number"]},"difficulty":{"oneOf":["null","number"]},"intent":{"oneOf":["null",{"literal":"informational"},{"literal":"commercial"},{"literal":"transactional"},{"literal":"navigational"},{"literal":"unknown"}]},"monthly_trend":{"array":{"ref":103}},"search_volume":{"oneOf":["null","number"]}}},
    {"object":{"month":"number","search_volume":{"oneOf":["null","number"]},"year":"number"}},
    {"object":{"cached":"boolean","cost_cents":"number","returned":"number","source":{"oneOf":[{"literal":"related"},{"literal":"suggestion"},{"literal":"idea"}]},"status":{"oneOf":[{"literal":"ok"},{"literal":"skipped"},{"literal":"failed"}]}},"optional":{"reason":{"oneOf":[{"literal":"budget_exhausted"},{"literal":"cost_limit"},{"literal":"in_progress"},{"literal":"needs_reauth"},{"literal":"no_source"},{"literal":"previous_source_failed"},{"literal":"provider_error"},{"literal":"rate_limited"},{"literal":"result_limit"},{"literal":"unsupported_location"}]}}},
    {"object":{"data":{"oneOf":[{"ref":106},{"ref":107}]}},"optional":{"meta":{"ref":54}}},
    {"object":{"cached":"boolean","cached_until":{"oneOf":["null","string"]},"cost_cents":"number","estimate":{"literal":true},"estimated_cost_cents":"number","include_subdomains":"boolean","provider":"string","target":"string","target_scope":{"oneOf":[{"literal":"site"},{"literal":"page"}]}}},
    {"object":{"cached":"boolean","cached_until":"string","cost_cents":"number","fetched_at":"string","fetched_row_count":"number","history":{"array":{"ref":108}},"include_subdomains":"boolean","provider":"string","rows":{"array":{"ref":109}},"summary":{"ref":110},"target":"string","target_scope":{"oneOf":[{"literal":"site"},{"literal":"page"}]},"total_rows_available":"number"},"optional":{"estimate":"unknown"}},
    {"object":{"lost_links":"number","month":"string","new_links":"number"}},
    {"object":{"anchor":"string","domain_authority":"number","first_seen":"string","flags":{"array":{"oneOf":[{"literal":"nofollow"},{"literal":"ugc"},{"literal":"sponsored"},{"literal":"image"},{"literal":"sitewide"}]}},"links_count":"number","lost_at":{"oneOf":["null","string"]},"source_domain":"string","source_url":"string","spam_score":"number","status":{"oneOf":[{"literal":"active"},{"literal":"new"},{"literal":"lost"}]},"target_url":"string"}},
    {"object":{"backlinks_total":"number","broken_backlinks":"number","broken_pages":"number","dofollow_pct":"number","domain_rank":"number","lost_backlinks":"number","lost_referring_domains":"number","new_backlinks":"number","new_referring_domains":"number","referring_domains_total":"number","referring_pages":"number","spam_score":"number"}},
    {"object":{"data":{"ref":107}},"optional":{"meta":{"ref":54}}},
    {"object":{"data":{"oneOf":[{"ref":113},{"ref":114}]}},"optional":{"meta":{"ref":54}}},
    {"object":{"cached":"boolean","estimate":{"literal":true},"estimated_cost_cents":"number","fresh_estimated_cost_cents":"number","history_estimated_cost_cents":"number","history_mode":{"literal":"lazy"},"keyword_page_estimated_cost_cents":"number","language_code":"string","location_code":"number","page_page_estimated_cost_cents":"number","provider":"string","scope":{"oneOf":[{"literal":"root"},{"literal":"subdomain"}]},"target":"string"}},
    {"object":{"cached":"boolean","cached_until":"string","cost_cents":"number","fetched_at":"string","history_mode":{"literal":"lazy"},"keywords":{"oneOf":[{"ref":115},{"ref":116}]},"language_code":"string","location_code":"number","overview":{"oneOf":["null",{"ref":119}]},"pages":{"oneOf":[{"ref":115},{"ref":120}]},"previous_fetched_at":{"oneOf":["null","string"]},"previous_overview":{"oneOf":["null",{"ref":119}]},"previous_source_snapshot_at":{"oneOf":["null","string"]},"provider":"string","scope":{"oneOf":[{"literal":"root"},{"literal":"subdomain"}]},"source_snapshot_at":{"oneOf":["null","string"]},"state":{"oneOf":[{"literal":"ok"},{"literal":"no_data"},{"literal":"partial"}]},"target":"string"}},
    {"object":{"cost_cents":"number","ok":{"literal":false},"reason":{"oneOf":[{"literal":"budget_exhausted"},{"literal":"in_progress"},{"literal":"needs_reauth"},{"literal":"no_source"},{"literal":"rate_limited"},{"literal":"unsupported_location"},{"literal":"cost_limit_exceeded"},{"literal":"lookup_failed"},{"literal":"snapshot_expired"}]}},"optional":{"reset_at":"number"}},
    {"object":{"cached":"boolean","cost_cents":"number","data":{"ref":117},"fetched_at":"string","ok":{"literal":true}}},
    {"object":{"cost_cents":"number","rows":{"array":{"ref":118}},"total_count":{"oneOf":["null","number"]}}},
    {"object":{"cpc_cents":{"oneOf":["null","number"]},"difficulty":{"oneOf":["null","number"]},"estimated_traffic":{"oneOf":["null","number"]},"intent":{"oneOf":["null",{"literal":"informational"},{"literal":"commercial"},{"literal":"transactional"},{"literal":"navigational"}]},"keyword":"string","position":{"oneOf":["null","number"]},"rank_absolute":{"oneOf":["null","number"]},"rank_absolute_delta":{"oneOf":["null","number"]},"ranking_url":{"oneOf":["null","string"]},"search_volume":{"oneOf":["null","number"]},"serp_features":{"array":"string"}}},
    {"object":{"count":{"oneOf":["null","number"]},"estimated_traffic_cost_cents":{"oneOf":["null","number"]},"etv":{"oneOf":["null","number"]},"is_down":"number","is_lost":"number","is_new":"number","is_up":"number","pos1":"number","pos11_20":"number","pos21_30":"number","pos2_3":"number","pos31_40":"number","pos41_50":"number","pos4_10":"number","pos51_60":"number","pos61_70":"number","pos71_80":"number","pos81_90":"number","pos91_100":"number"}},
    {"object":{"cached":"boolean","cost_cents":"number","data":{"ref":121},"fetched_at":"string","ok":{"literal":true}}},
    {"object":{"cost_cents":"number","rows":{"array":{"ref":122}},"total_count":"number"}},
    {"object":{"etv":{"oneOf":["null","number"]},"etv_delta_pct":{"oneOf":["null","number"]},"keyword_count":{"oneOf":["null","number"]},"path":"string","top_keyword":{"oneOf":["null","string"]},"top_keyword_position":{"oneOf":["null","number"]}}},
    {"object":{"data":{"ref":124}},"optional":{"meta":{"ref":54}}},
    {"object":{"cached":"boolean","cost_cents":"number","data":{"array":{"ref":125}},"fetched_at":"string"}},
    {"object":{"metrics":{"ref":119},"month":"number","year":"number"}},
    {"object":{"data":{"ref":127}},"optional":{"meta":{"ref":54}}},
    {"object":{"cached":"boolean","cost_cents":"number","data":{"ref":117},"fetched_at":"string"}},
    {"object":{"data":{"ref":129}},"optional":{"meta":{"ref":54}}},
    {"object":{"cached":"boolean","cost_cents":"number","data":{"ref":121},"fetched_at":"string"}},
    {"object":{"cached_count":"number","connections":{"array":{"ref":99}},"cost_cents":"number","fetched_at":"string","fetched_count":"number","provider":"string","rows":{"array":{"ref":131}},"total_count":"number"},"optional":{"estimate":"boolean","estimated_cost_cents":"number","fetched_count_estimate":"number"}},
    {"object":{"keyword":"string","competition":{"oneOf":["null","number"]},"cpc_cents":{"oneOf":["null","number"]},"difficulty":{"oneOf":["null","number"]},"intent":{"oneOf":["null",{"literal":"informational"},{"literal":"commercial"},{"literal":"transactional"},{"literal":"navigational"},{"literal":"unknown"}]},"monthly_trend":{"array":{"ref":103}},"search_volume":{"oneOf":["null","number"]}}},
    {"object":{"data":{"array":{"ref":133}},"meta":{"ref":68}}},
    {"object":{"checked_at":"string","id":"string","keyword":"string","keyword_id":"string","position":{"oneOf":["null","number"]},"previous_position":{"oneOf":["null","number"]},"ranking_url":{"oneOf":["null","string"]}}},
    {"object":{"data":{"array":{"ref":135}},"meta":{"ref":68}}},
    {"object":{"enabled":"boolean","id":"string","latest_snapshot":{"oneOf":["null",{"ref":136}]},"project_id":"string","sitemap_url":{"oneOf":["null","string"]},"status":{"oneOf":[{"literal":"active"},{"literal":"disabled"},{"literal":"pending"}]}}},
    {"object":{"fetched_at":"string","sitemap_url":"string","url_count":"number"}},
    {"object":{"data":{"array":{"ref":138}},"meta":{"ref":68}}},
    {"object":{"attempts":{"oneOf":["null",{"array":{"ref":139}}]},"checked_at":"string","cost_cents":{"oneOf":["null","number"]},"error":{"oneOf":["null","string"]},"id":"string","keyword_id":"string","position":{"oneOf":["null","number"]},"previous_position":{"oneOf":["null","number"]},"provider":"string","ranking_url":{"oneOf":["null","string"]},"run_id":{"oneOf":["null","string"]},"status":{"oneOf":[{"literal":"failed"},{"literal":"completed"},{"literal":"running"}]}}},
    {"object":{"message":"string","provider":"string"}},
    {"object":{"id":"string","status":{"literal":"queued"}}},
    {"object":{"created_at":"string","happened_at":"string","id":"string","keyword_id":{"oneOf":["null","string"]},"payload":{"oneOf":["null",{"ref":54}]},"project_id":"string","public_id":"string","severity":{"oneOf":[{"literal":"critical"},{"literal":"info"},{"literal":"warning"}]},"source":{"oneOf":[{"literal":"manual"},{"literal":"api"},{"literal":"cms"},{"literal":"deploy"},{"literal":"rank_tracker"},{"literal":"search_analytics"},{"literal":"search_engine_status"},{"literal":"sitemap"},{"literal":"url_inspection"}]},"type":"string","url":{"oneOf":["null","string"]}}},
    {"object":{"data":{"array":{"ref":141}},"meta":{"ref":68}}},
    {"object":{"offset":"number","rows":{"array":{"ref":144}},"total_count":"number"}},
    {"object":{"bounce_rate":{"oneOf":["null","number"]},"created_at":"string","date":"string","engagement_rate":{"oneOf":["null","number"]},"key_events":{"oneOf":["null","number"]},"path":"string","provider":"string","scroll_depth":{"oneOf":["null","number"]},"sessions":"number","updated_at":"string","visit_duration_seconds":{"oneOf":["null","number"]},"visitors":{"oneOf":["null","number"]},"window_days":"number"}},
    {"object":{"connection":{"ref":146},"rows":{"array":{"ref":147}}}},
    {"object":{"id":"string","label":"string","provider":"string"}},
    {"object":{"clicks":"number","ctr":"number","impressions":"number","position":"number","query":"string"},"optional":{"page":{"oneOf":["null","string"]}}},
    {"object":{"connections":"number","keyword_snapshots":"number","page_snapshots":"number","project_id":"string","runs":{"array":{"ref":149}},"skipped":{"array":{"ref":150}}}},
    {"object":{"connection_id":"string","provider":"string","rows_fetched":"number","rows_matched":"number","rows_upserted":"number","status":{"oneOf":[{"literal":"failed"},{"literal":"succeeded_with_data"},{"literal":"succeeded_empty"},{"literal":"deferred_rate_limit"},{"literal":"not_applicable"}]},"truncated":"boolean"},"optional":{"error":"string","error_class":"string"}},
    {"object":{"provider":"string","reason":{"oneOf":[{"literal":"rate_limited"},{"literal":"no_capability"}]}}},
    {"object":{"data":{"array":{"oneOf":[{"ref":152},{"ref":153},{"ref":154}]}},"meta":{"ref":68}}},
    {"object":{"channels":{"array":{"oneOf":[{"literal":"email"},{"literal":"slack"},{"literal":"webhook"}]}},"condition_type":{"oneOf":[{"literal":"change_pct"},{"literal":"competitor_overtake"},{"literal":"ctr_drop"},{"literal":"downtrend"},{"literal":"enters_top_n"},{"literal":"exits_top_n"},{"literal":"position_drop"},{"literal":"serp_feature"},{"literal":"threshold"},{"literal":"url_mismatch"}]},"enabled":"boolean","id":"string","name":"string","recipient_ids":{"array":"string"},"target_ids":{"array":"string"},"target_type":{"literal":"keyword"}},"optional":{"change_pct":{"oneOf":["null","string","number"]},"channel":"string","condition":"string","competitor_domain":{"oneOf":["null","string"]},"created_at":"string","fires":"string","period":"string","scope":"string","serp_feature":{"oneOf":["null","string"]},"severity":{"oneOf":[{"literal":"info"},{"literal":"warning"},{"literal":"urgent"}]},"status":{"oneOf":[{"ref":1},{"literal":"active"},{"literal":"paused"}]},"threshold_position":{"oneOf":["null","number"]},"top_n":{"oneOf":["null","number"]},"updated_at":"string"}},
    {"object":{"channels":{"array":{"oneOf":[{"literal":"email"},{"literal":"slack"},{"literal":"webhook"}]}},"condition_type":{"oneOf":[{"literal":"change_pct"},{"literal":"competitor_overtake"},{"literal":"ctr_drop"},{"literal":"downtrend"},{"literal":"enters_top_n"},{"literal":"exits_top_n"},{"literal":"position_drop"},{"literal":"serp_feature"},{"literal":"threshold"},{"literal":"url_mismatch"}]},"enabled":"boolean","id":"string","name":"string","recipient_ids":{"array":"string"},"target_ids":{"array":"string"},"target_type":{"literal":"tag"}},"optional":{"change_pct":{"oneOf":["null","string","number"]},"channel":"string","condition":"string","competitor_domain":{"oneOf":["null","string"]},"created_at":"string","fires":"string","period":"string","scope":"string","serp_feature":{"oneOf":["null","string"]},"severity":{"oneOf":[{"literal":"info"},{"literal":"warning"},{"literal":"urgent"}]},"status":{"oneOf":[{"ref":1},{"literal":"active"},{"literal":"paused"}]},"threshold_position":{"oneOf":["null","number"]},"top_n":{"oneOf":["null","number"]},"updated_at":"string"}},
    {"object":{"channels":{"array":{"oneOf":[{"literal":"email"},{"literal":"slack"},{"literal":"webhook"}]}},"condition_type":{"oneOf":[{"literal":"change_pct"},{"literal":"competitor_overtake"},{"literal":"ctr_drop"},{"literal":"downtrend"},{"literal":"enters_top_n"},{"literal":"exits_top_n"},{"literal":"position_drop"},{"literal":"serp_feature"},{"literal":"threshold"},{"literal":"url_mismatch"}]},"enabled":"boolean","id":"string","name":"string","recipient_ids":{"array":"string"},"target_ids":{"emptyArray":true},"target_type":{"literal":"all"}},"optional":{"change_pct":{"oneOf":["null","string","number"]},"channel":"string","condition":"string","competitor_domain":{"oneOf":["null","string"]},"created_at":"string","fires":"string","period":"string","scope":"string","serp_feature":{"oneOf":["null","string"]},"severity":{"oneOf":[{"literal":"info"},{"literal":"warning"},{"literal":"urgent"}]},"status":{"oneOf":[{"ref":1},{"literal":"active"},{"literal":"paused"}]},"threshold_position":{"oneOf":["null","number"]},"top_n":{"oneOf":["null","number"]},"updated_at":"string"}},
    {"object":{"deleted":"boolean"}},
    {"object":{"data":{"array":{"ref":157}},"meta":{"ref":68}}},
    {"object":{"action":"string","ctas":{"array":"string"},"current":"string","headline":"string","id":"string","keyword":"string","previous":"string","rule":"string","severity":{"oneOf":[{"literal":"info"},{"literal":"warning"},{"literal":"urgent"}]},"unread":"boolean","when":"string"}},
    {"object":{"muted":{"literal":true},"snoozed_until":{"oneOf":["null","string"]}}},
    {"object":{"updated":"number"}},
    {"object":{"data":{"array":{"ref":161}},"meta":{"ref":68}}},
    {"object":{"color":{"oneOf":[{"ref":1},{"literal":"accent"},{"literal":"blue"},{"literal":"purple"}]},"email":"string","id":"string","initials":"string","name":"string","role":{"oneOf":[{"literal":"Admin"},{"literal":"Editor"},{"literal":"Owner"},{"literal":"Viewer"}]},"role_value":{"oneOf":[{"literal":"admin"},{"literal":"member"},{"literal":"owner"},{"literal":"viewer"}]}}},
    {"object":{"data":{"array":{"ref":163}},"meta":{"ref":68}}},
    {"object":{"email":"string","expires_label":"string","id":"string","invited_label":"string","role":{"oneOf":[{"literal":"Admin"},{"literal":"Editor"},{"literal":"Owner"},{"literal":"Viewer"}]},"role_value":{"oneOf":[{"literal":"admin"},{"literal":"member"},{"literal":"viewer"}]}}},
    {"object":{"expires_at":"string","id":"string","invite_link":"string"}},
    {"object":{"id":"string"}},
    {"object":{"expires_at":"string","id":"string","invite_link":"string"}},
    {"object":{"id":"string","role":{"oneOf":[{"literal":"admin"},{"literal":"member"},{"literal":"viewer"}]}}},
    {"object":{"id":"string"}},
    {"object":{"data":{"ref":170}},"optional":{"meta":{"ref":54}}},
    {"object":{"updated_at":{"oneOf":["null","string"]},"business":"string","audience":"string","products":"string","goals":"string","agent_rules":"string"}},
    {"object":{"data":{"array":{"ref":172}},"meta":{"ref":68}}},
    {"object":{"id":"string","title":"string","kind":"string","created_at":"string"}},
    {"object":{"data":{"ref":174}},"optional":{"meta":{"ref":54}}},
    {"object":{"body":{"ref":175},"provenance":{"ref":175},"id":"string","title":"string","kind":"string","created_at":"string"}},
    {"object":{}},
    {"object":{"data":{"oneOf":[{"ref":177},{"ref":178}]}},"optional":{"meta":{"ref":54}}},
    {"object":{"ok":{"literal":true},"estimate":{"literal":true},"estimated_cost_cents":"number","evidence":{"oneOf":[{"literal":"observed_dataset"},{"literal":"synthetic_prompt_test"}]}}},
    {"object":{"ok":{"literal":true},"estimate":{"literal":false},"cached":"boolean","report_id":"string","cost_cents":"number","result":{"ref":179}}},
    {"object":{"evidence":{"oneOf":[{"literal":"observed_dataset"},{"literal":"synthetic_prompt_test"}]},"rows":{"array":{"ref":180}},"total_available":{"oneOf":["null","number"]},"truncated":"boolean","fetched_at":"string","cost_cents":"number","cost_status":{"oneOf":[{"literal":"unknown"},{"literal":"confirmed"}]},"failure":{"oneOf":["null","string"]}}},
    {"object":{"prompt":"string","model":"string","answer":"string","observed_at":{"oneOf":["null","string"]},"brand_mentioned":"boolean","domain_cited":"boolean","citations":{"array":{"ref":181}}},"optional":{"content_truncated":"boolean"}},
    {"object":{"title":"string","url":"string","target_domain":"boolean"}},
    {"object":{"data":{"array":{"ref":172}}},"optional":{"meta":{"ref":54}}},
    {"object":{"data":{"ref":184}},"optional":{"meta":{"ref":54}}},
    {"object":{"id":"string","created_at":"string","cached":"boolean","result":{"ref":185}}},
    {"object":{"version":{"literal":1},"target":"string","started_at":"string","completed_at":"string","state":{"oneOf":[{"literal":"partial"},{"literal":"complete"}]},"stop_reason":{"oneOf":[{"literal":"finished"},{"literal":"page_limit"},{"literal":"time_limit"},{"literal":"request_limit"}]},"limits":{"ref":186},"requests":"number","pages":{"array":{"ref":187}},"summary":{"ref":190},"limitations":{"array":"string"}}},
    {"object":{"max_pages":"number","max_requests":"number","max_duration_ms":"number","max_page_bytes":"number"}},
    {"object":{"url":"string","final_url":"string","status":{"oneOf":["null","number"]},"response_time_ms":"number","title":{"oneOf":["null","string"]},"description":{"oneOf":["null","string"]},"canonical":{"oneOf":["null","string"]},"headings":{"array":{"ref":188}},"h1_count":"number","indexable":"boolean","robots":{"oneOf":["null","string"]},"internal_link_count":"number","external_link_count":"number","internal_links":{"array":"string"},"image_count":"number","missing_alt_count":"number","issues":{"array":{"ref":189}}}},
    {"object":{"level":"number","text":"string"}},
    {"object":{"code":"string","severity":{"oneOf":[{"literal":"info"},{"literal":"warning"},{"literal":"error"}]},"message":"string"}},
    {"object":{"pages":"number","errors":"number","warnings":"number","indexable":"number"}},
    {"object":{"data":{"array":{"ref":192}},"meta":{"ref":193}}},
    {"object":{"fresh_until":"string","kind":{"oneOf":[{"literal":"backlinks"},{"literal":"domain_overview"},{"literal":"keyword_research"}]},"saved_at":"string","state":{"oneOf":[{"literal":"fresh"},{"literal":"stale"}]}},"optional":{"country_code":"string","include_clickstream":"boolean","include_subdomains":"boolean","language_code":"string","location_code":"number","mode":"string","result_limit":"number","seed":"string","target":"string","target_scope":"string"}},
    {"object":{"freshness_days":"number"}},
    {"object":{"data":{"oneOf":[{"ref":195},{"ref":196},{"ref":197}]}}},
    {"object":{"cached":"boolean","cached_until":"string","cost_cents":"number","fetched_at":"string","fetched_row_count":"number","history":{"array":{"ref":108}},"include_subdomains":"boolean","provider":"string","rows":{"array":{"ref":109}},"summary":{"ref":110},"target":"string","target_scope":{"oneOf":[{"literal":"site"},{"literal":"page"}]},"total_rows_available":"number","fresh_until":"string","saved_at":"string","stale":"boolean","state":{"oneOf":[{"literal":"fresh"},{"literal":"stale"}]}},"optional":{"estimate":"unknown"}},
    {"object":{"cached":"boolean","cost_cents":"number","country_code":{"oneOf":["null","string"]},"data_state":{"oneOf":[{"literal":"ok"},{"literal":"no_data"},{"literal":"partial"}]},"fetched_at":"string","fresh_until":"string","history":{"oneOf":["null",{"array":{"ref":125}}]},"keywords":{"oneOf":["null",{"ref":117}]},"language_code":"string","location_code":"number","overview":{"oneOf":["null",{"ref":119}]},"pages":{"oneOf":["null",{"ref":121}]},"partial":"boolean","previous_fetched_at":{"oneOf":["null","string"]},"previous_overview":{"oneOf":["null",{"ref":119}]},"previous_source_snapshot_at":{"oneOf":["null","string"]},"provider":"string","saved_at":"string","scope":{"oneOf":[{"literal":"root"},{"literal":"subdomain"}]},"source_snapshot_at":{"oneOf":["null","string"]},"stale":"boolean","state":{"oneOf":[{"literal":"fresh"},{"literal":"stale"}]},"target":"string"}},
    {"object":{"cached":"boolean","cost_cents":"number","country_code":"string","fetched_at":"string","fresh_until":"string","include_clickstream":"boolean","language_code":"string","mode":"string","partial":"boolean","provider":"string","request_key":"string","result_limit":"number","rows":{"array":{"ref":198}},"saved_at":"string","seed":"string","sources":{"array":{"ref":200}},"stale":"boolean","state":{"oneOf":[{"literal":"fresh"},{"literal":"stale"}]}}},
    {"object":{"already_saved":"boolean","already_tracked":"boolean","competition":{"oneOf":["null","number"]},"cpc_cents":{"oneOf":["null","number"]},"difficulty":{"oneOf":["null","number"]},"intent":{"oneOf":["null",{"literal":"informational"},{"literal":"commercial"},{"literal":"transactional"},{"literal":"navigational"},{"literal":"unknown"}]},"keyword":"string","monthly_trend":{"array":{"ref":199}},"search_volume":{"oneOf":["null","number"]},"source":{"oneOf":[{"literal":"related"},{"literal":"suggestion"},{"literal":"idea"}]}}},
    {"object":{"month":"number","search_volume":{"oneOf":["null","number"]},"year":"number"}},
    {"object":{"cached":"boolean","cost_cents":"number","returned":"number","source":{"oneOf":[{"literal":"related"},{"literal":"suggestion"},{"literal":"idea"}]},"status":{"oneOf":[{"literal":"ok"},{"literal":"skipped"},{"literal":"failed"}]}},"optional":{"reason":{"oneOf":[{"literal":"budget_exhausted"},{"literal":"cost_limit"},{"literal":"in_progress"},{"literal":"needs_reauth"},{"literal":"no_source"},{"literal":"previous_source_failed"},{"literal":"provider_error"},{"literal":"rate_limited"},{"literal":"result_limit"},{"literal":"unsupported_location"}]}}},
    {"object":{"data":{"array":{"ref":202}},"meta":{"ref":68}}},
    {"object":{"connection_id":"string","credential_source":{"oneOf":[{"literal":"own"},{"literal":"hosted"}]},"credits":{"ref":203},"own":{"ref":206},"provider":"string","source":{"oneOf":[{"literal":"connection"},{"literal":"legacy_project"},{"literal":"none"}]}}},
    {"object":{"app":{"oneOf":["null",{"ref":204}]},"programmatic":{"oneOf":["null",{"ref":205}]}}},
    {"object":{"amount_per_month":"number","unit":{"literal":"cents"}}},
    {"object":{"amount_per_month":"number","unit":{"literal":"cents"}}},
    {"object":{"app":{"oneOf":["null",{"ref":207}]},"programmatic":{"oneOf":["null",{"ref":208}]}}},
    {"object":{"amount_per_month":"number","unit":{"oneOf":[{"literal":"cents"},{"literal":"units"}]}}},
    {"object":{"amount_per_month":"number","unit":{"oneOf":[{"literal":"cents"},{"literal":"units"}]}}},
    {"object":{"data":{"array":{"ref":210}},"meta":{"ref":68}}},
    {"object":{"category_id":"string","category_title":"string","description":"string","drawer":{"ref":211},"icon":{"oneOf":[{"literal":"chart"},{"literal":"database"},{"literal":"globe"},{"literal":"link"},{"literal":"magnifier"},{"literal":"table"},{"literal":"trend"}]},"id":{"oneOf":[{"ref":1},{"literal":"dataforseo"},{"literal":"ga4"},{"literal":"gsc"},{"literal":"plausible"},{"literal":"serpapi"}]},"meta":{"array":{"ref":212}},"name":"string","status":{"oneOf":[{"ref":1},{"literal":"connected"},{"literal":"optional"},{"literal":"planned"},{"literal":"ready"}]},"tint":"string"},"optional":{"enabled":"boolean","logo_domain":"string","primary":"boolean","priority":"number","secondary_action":"string"}},
    {"object":{"activities":{"array":{"ref":212}},"cost_help":"string","credential_fields":{"array":{"ref":213}},"defaults":{"ref":214},"env_hint":"string","primary_toggle_label":"string"}},
    {"object":{"label":"string","value":"string"}},
    {"object":{"label":"string","name":{"oneOf":[{"ref":1},{"literal":"login"},{"literal":"secret"}]},"placeholder":"string"},"optional":{"type":{"oneOf":[{"ref":1},{"literal":"password"},{"literal":"text"}]}}},
    {"object":{"cost_per_check":"number","depth":"string","device":"string","language":"string","location":"string","login":"string","primary":"boolean","secret":"string"},"optional":{"enabled":"boolean","priority":"number"}},
    {"object":{"cost_per_check_cents":{"oneOf":["null","string","number"]},"created_at":"string","enabled":"boolean","id":"string","is_primary":"boolean","kind":{"oneOf":[{"literal":"analytics"},{"literal":"enrichment"},{"literal":"serp"}]},"last_used_at":{"oneOf":["null","string"]},"priority":"number","project_id":"string","provider":{"oneOf":[{"ref":1},{"literal":"dataforseo"},{"literal":"ga4"},{"literal":"gsc"},{"literal":"plausible"},{"literal":"serpapi"}]},"status":{"oneOf":[{"ref":1},{"literal":"connected"},{"literal":"optional"},{"literal":"planned"},{"literal":"ready"}]},"updated_at":"string"},"optional":{"credentials_hash":{"oneOf":["null","string"]}}},
    {"object":{"message":"string","ok":"boolean"},"optional":{"balance":"number"}},
    {"object":{"ok":"boolean"}},
    {"object":{"data":{"array":{"ref":219}},"meta":{"ref":68}}},
    {"object":{"config":{"oneOf":[{"ref":220},{"ref":223}]},"created_at":"string","created_by_id":{"oneOf":["null","string"]},"id":"string","name":"string","surface":{"oneOf":[{"literal":"competitors"},{"literal":"keywords"}]}}},
    {"object":{"filters":{"ref":221},"scope":{"ref":222},"surface":{"literal":"competitors"},"version":{"literal":1}}},
    {"object":{"excluded_keyword_ids":{"array":"string"},"position":{"oneOf":[{"literal":"all"},{"literal":"top10"},{"literal":"top3"}]},"tag":{"oneOf":["null","string"]}}},
    {"object":{"device":{"oneOf":[{"literal":"desktop"},{"literal":"mobile"}]},"engine":{"literal":"google"},"location_id":"string"}},
    {"object":{"filters":{"ref":224},"lens":{"ref":225},"search":"string","surface":{"literal":"keywords"},"version":{"literal":1}}},
    {"object":{"change":{"oneOf":[{"literal":"new"},{"literal":"lost"},{"literal":"any"},{"literal":"down"},{"literal":"up"}]},"contains":"string","intents":{"array":"string"},"last_check":{"oneOf":[{"literal":"failed"},{"literal":"completed"},{"literal":"running"},{"literal":"any"}]},"position":{"array":{"oneOf":[{"literal":"top10"},{"literal":"top3"},{"literal":"11-50"},{"literal":"51-100"}]}},"serp":{"array":{"oneOf":[{"literal":"image"},{"literal":"ai"},{"literal":"featured"},{"literal":"paa"},{"literal":"sitelinks"},{"literal":"video"}]}},"tags":{"array":"string"},"topics":{"array":"string"},"url_changed":"boolean","vol_max":"number","vol_min":"number","wrong_url":"boolean"}},
    {"object":{"device":{"oneOf":[{"literal":"desktop"},{"literal":"mobile"},{"literal":"all"}]},"location_id":{"oneOf":["null","string"]}}},
    {"object":{"deleted":"boolean"}},
    {"object":{"data":{"array":{"ref":228}},"meta":{"ref":68}}},
    {"object":{"cpc":{"oneOf":["null","number"]},"difficulty":{"oneOf":["null","number"]},"id":"string","intent":{"oneOf":["null","string"]},"location":"string","saved_at":"string","source_seed":{"oneOf":["null","string"]},"text":"string","trend":{"array":{"ref":229}},"variant_count":"number","volume":{"oneOf":["null","number"]}}},
    {"object":{"month":"number","search_volume":{"oneOf":["null","number"]},"year":"number"}},
    {"object":{"duplicate_count":"number","results":{"array":{"ref":231}},"saved_count":"number"}},
    {"object":{"keyword":"string","status":{"oneOf":[{"literal":"created"},{"literal":"skipped"}]}}},
    {"object":{"removed_count":"number"}},
    {"object":{"meta":{"ref":234},"data":{"array":{"ref":241}}}},
    {"object":{"markets":{"array":{"ref":235}},"suggestions":{"array":{"ref":240}},"next_cursor":{"oneOf":["null","string"]}}},
    {"object":{"checked_keyword_count":"number","columns":{"array":{"ref":236}},"competitor_count":"number","country":"string","device":"string","engine":"string","has_rank_data":"boolean","key":"string","rows":{"array":{"ref":237}},"shares":{"array":{"ref":239}},"shared_keyword_count":"number","tracked_keyword_count":"number"}},
    {"object":{"domain":"string","kind":{"oneOf":[{"literal":"Managed"},{"literal":"You"}]},"label":"string"},"optional":{"id":"string"}},
    {"object":{"gap":{"oneOf":["null","number"]},"keyword":"string","ranks":{"ref":238}}},
    {"object":{},"optional":{"you":{"oneOf":["null","number"]}}},
    {"object":{"color":"string","domain":"string","initials":"string","kind":{"oneOf":[{"literal":"Managed"},{"literal":"You"}]},"label":"string","share_of_voice":"number","shared_keywords":"number"},"optional":{"id":"string"}},
    {"object":{"domain":"string","initials":"string","overlap":"number"}},
    {"object":{"domain":"string","id":"string","label":{"oneOf":["null","string"]}},"optional":{"initials":"string"}},
    {"object":{"removed":"boolean"}},
    {"object":{"alert_email":"boolean","alert_in_app":"boolean","alert_slack":"boolean","alert_webhook":"boolean","check_email":"boolean","check_in_app":"boolean","import_email":"boolean","import_in_app":"boolean","invite_email":"boolean","invite_in_app":"boolean","project_id":"string"},"optional":{"email":"string","email_verification":{"oneOf":[{"literal":"unverified"},{"literal":"verified"}]},"slack_available":"boolean","webhook_available":"boolean"}},
    {"object":{"meta":{"ref":245},"data":{"array":{"ref":247}}}},
    {"object":{"import_job":{"ref":246},"next_cursor":{"oneOf":["null","string"]}}},
    {"object":{"counts":"unknown","created_at":{"oneOf":["null","string"]},"error":{"oneOf":["null","string"]},"finished_at":{"oneOf":["null","string"]},"id":{"oneOf":["null","string"]},"progress":"number","started_at":{"oneOf":["null","string"]},"state":{"oneOf":[{"literal":"failed"},{"literal":"done"},{"literal":"idle"},{"literal":"importing"},{"literal":"receiving"}]}}},
    {"object":{"created_at":"string","expires_at":"string","id":"string","scope":{"oneOf":[{"literal":"keywords"},{"literal":"full"}]},"single_use":"boolean"},"optional":{"created_by":{"ref":248}}},
    {"object":{"email":"string","name":"string"}},
    {"object":{"import_job":{"ref":246},"token":"string","created_at":"string","expires_at":"string","id":"string","scope":{"oneOf":[{"literal":"keywords"},{"literal":"full"}]},"single_use":"boolean"},"optional":{"created_by":{"ref":248}}},
    {"object":{"id":"string","revoked_at":"string"}},
    {"object":{"app_version":"string","latest_migration":{"oneOf":["null","string"]},"schema_versions_supported":{"array":"number"}}},
    {"object":{"counts":{"ref":253},"job_id":"string","state":{"literal":"done"}}},
    {"object":{}},
    {"object":{"chunk_limits":{"ref":255},"session_id":"string","state":{"literal":"receiving"}}},
    {"object":{"max_body_bytes":"number","max_history_rows":"number","max_keywords":"number"}},
    {"object":{"chunk_count":"number","chunks_received":"number","state":{"literal":"receiving"}}}
  ]
};
