// Generated from SDK response types. Do not edit by hand.
// Keep this in sync when a public response type or operation changes.
import type { SuccessContractData } from "./response-contract.js";

// biome-ignore format: Generated contract graph; one schema per line keeps changes reviewable.
export const successContractData: SuccessContractData = {
  "operations": {
    "GET /health": {"ref":0},
    "GET /liveness": {"ref":51},
    "GET /readiness": {"ref":52},
    "GET /openapi.json": {"ref":53},
    "GET /capabilities": {"ref":55},
    "GET /llms.txt": "string",
    "GET /provider-rates": {"ref":57},
    "GET /cost-estimate": {"ref":62},
    "GET /locations/search": {"ref":66},
    "GET /me": {"ref":69},
    "PATCH /me": {"ref":69},
    "GET /me/tokens": {"ref":71},
    "POST /me/tokens": {"ref":73},
    "DELETE /me/tokens/*": {"ref":72},
    "GET /projects": {"ref":74},
    "POST /projects": {"ref":75},
    "GET /projects/*": {"ref":75},
    "PATCH /projects/*": {"ref":75},
    "DELETE /projects/*": {"ref":75},
    "GET /projects/*/defaults": {"ref":76},
    "GET /projects/*/overview": {"ref":77},
    "POST /projects/*/keyword-matches": {"ref":79},
    "PATCH /projects/*/defaults": {"ref":76},
    "GET /api-keys": {"ref":83},
    "POST /api-keys": {"ref":85},
    "DELETE /api-keys/*": {"ref":84},
    "GET /projects/*/api-keys": {"ref":83},
    "POST /projects/*/api-keys": {"ref":85},
    "GET /projects/*/webhooks": {"ref":86},
    "POST /projects/*/webhooks": {"ref":87},
    "PATCH /projects/*/webhooks/*": {"ref":87},
    "DELETE /projects/*/webhooks/*": {"ref":87},
    "GET /projects/*/keywords": {"ref":88},
    "POST /projects/*/keywords": {"ref":93},
    "GET /keywords/*": {"ref":89},
    "PATCH /keywords/*": {"ref":89},
    "DELETE /keywords/*": {"ref":89},
    "POST /keywords/bulk": {"ref":95},
    "GET /projects/*/ranked-keyword-suggestions": {"ref":97},
    "GET /projects/*/keyword-research": {"oneOf":[{"ref":100},{"ref":103}]},
    "GET /projects/*/backlinks": {"ref":107},
    "POST /projects/*/backlinks/rows": {"ref":113},
    "POST /projects/*/domain-overview/analyze": {"ref":114},
    "POST /projects/*/domain-overview/history": {"ref":125},
    "POST /projects/*/domain-overview/keywords": {"ref":128},
    "POST /projects/*/domain-overview/pages": {"ref":130},
    "POST /projects/*/keyword-metrics": {"ref":132},
    "GET /projects/*/exports/rank-history": {"ref":134},
    "GET /projects/*/sitemap-monitors": {"ref":136},
    "PATCH /projects/*/sitemap-monitors/*": {"ref":137},
    "GET /keywords/*/rank-checks": {"ref":139},
    "POST /keywords/*/checks": {"oneOf":[{"ref":140},{"ref":142}]},
    "GET /rank-checks/*": {"ref":140},
    "POST /signals": {"ref":143},
    "GET /projects/*/signals": {"ref":144},
    "GET /projects/*/analytics/traffic-snapshots": {"ref":145},
    "GET /projects/*/analytics/query-stats": {"ref":147},
    "POST /projects/*/analytics/sync": {"ref":150},
    "GET /projects/*/alert-rules": {"ref":153},
    "POST /projects/*/alert-rules": {"oneOf":[{"ref":154},{"ref":155},{"ref":156}]},
    "PATCH /alert-rules/*": {"oneOf":[{"ref":154},{"ref":155},{"ref":156}]},
    "DELETE /alert-rules/*": {"ref":157},
    "GET /projects/*/triggered-alerts": {"ref":158},
    "POST /projects/*/triggered-alerts/*/mute": {"ref":160},
    "POST /projects/*/triggered-alerts/mark-read": {"ref":161},
    "GET /projects/*/team/members": {"ref":162},
    "GET /projects/*/team/invites": {"ref":164},
    "POST /projects/*/team/invites": {"ref":166},
    "DELETE /projects/*/team/invites/*": {"ref":167},
    "DELETE /team/invites/*": {"ref":167},
    "POST /projects/*/team/invites/*/resend": {"ref":168},
    "PATCH /projects/*/team/members/*": {"ref":169},
    "DELETE /projects/*/team/members/*": {"ref":170},
    "GET /projects/*/ai-catalog": {"ref":171},
    "GET /projects/*/context": {"ref":179},
    "PATCH /projects/*/context": {"ref":179},
    "GET /projects/*/agent-reports": {"ref":181},
    "POST /projects/*/agent-reports": {"ref":183},
    "GET /projects/*/agent-reports/*": {"ref":183},
    "POST /projects/*/ai-visibility": {"ref":186},
    "POST /projects/*/prompt-explorer": {"ref":186},
    "GET /projects/*/site-audits": {"ref":192},
    "POST /projects/*/site-audits": {"ref":193},
    "GET /projects/*/site-audits/*": {"ref":193},
    "GET /projects/*/research/reports": {"ref":201},
    "GET /projects/*/research/reports/*": {"ref":204},
    "GET /projects/*/provider-budgets": {"ref":211},
    "PATCH /projects/*/providers/*/budgets": {"ref":212},
    "GET /projects/*/providers": {"ref":219},
    "POST /projects/*/providers/*/connect": {"ref":225},
    "POST /projects/*/providers/*/test": {"ref":226},
    "PATCH /projects/*/providers/*": {"ref":225},
    "DELETE /projects/*/providers/*": {"ref":227},
    "GET /projects/*/saved-views": {"ref":228},
    "POST /projects/*/saved-views": {"ref":229},
    "DELETE /projects/*/saved-views/*": {"ref":236},
    "DELETE /saved-views/*": {"ref":236},
    "GET /projects/*/saved-keywords": {"ref":237},
    "POST /projects/*/saved-keywords": {"ref":240},
    "DELETE /projects/*/saved-keywords/*": {"ref":242},
    "GET /projects/*/competitors": {"ref":243},
    "POST /projects/*/competitors": {"ref":251},
    "DELETE /projects/*/competitors/*": {"ref":252},
    "DELETE /competitors/*": {"ref":252},
    "GET /projects/*/notification-preferences": {"ref":253},
    "PATCH /projects/*/notification-preferences": {"ref":253},
    "GET /projects/*/migration-tokens": {"ref":254},
    "POST /projects/*/migration-tokens": {"ref":259},
    "DELETE /projects/*/migration-tokens/*": {"ref":260},
    "DELETE /migration-tokens/*": {"ref":260},
    "GET /cloud/import/compatibility": {"ref":261},
    "POST /cloud/import": {"ref":262},
    "POST /cloud/import/sessions": {"ref":264},
    "PUT /cloud/import/sessions/*/chunks/*": {"ref":266},
    "POST /cloud/import/sessions/*/finalize": {"ref":262},
    "GET /projects/*/ai-tracking/topics": {"ref":267},
    "POST /projects/*/ai-tracking/topics": {"ref":269},
    "PATCH /projects/*/ai-tracking/topics/*": {"ref":269},
    "DELETE /projects/*/ai-tracking/topics/*": {"ref":269},
    "GET /projects/*/ai-tracking/prompts": {"ref":270},
    "POST /projects/*/ai-tracking/prompts": {"ref":275},
    "PATCH /projects/*/ai-tracking/prompts/*": {"ref":275},
    "DELETE /projects/*/ai-tracking/prompts/*": {"ref":275},
    "GET /projects/*/ai-tracking/schedules": {"ref":276},
    "POST /projects/*/ai-tracking/schedules": {"ref":281},
    "PATCH /projects/*/ai-tracking/schedules/*": {"ref":281},
    "DELETE /projects/*/ai-tracking/schedules/*": {"ref":281},
    "POST /projects/*/ai-tracking/runs/preview": {"ref":282},
    "POST /projects/*/ai-tracking/runs": {"ref":284},
    "GET /projects/*/ai-tracking/runs": {"ref":286},
    "GET /projects/*/ai-tracking/runs/*": {"ref":284},
    "GET /projects/*/ai-tracking/runs/*/samples": {"ref":287},
    "POST /projects/*/ai-tracking/runs/*/cancel": {"ref":284},
    "POST /projects/*/ai-tracking/runs/*/retry": {"ref":284},
    "GET /projects/*/ai-tracking/history": {"ref":286},
    "GET /projects/*/ai-tracking/trends": {"ref":292},
    "GET /projects/*/ai-tracking/export": {"ref":296},
    "POST /projects/*/ai-tracking/suggestions": {"ref":299},
    "POST /projects/*/ai-tracking/suggestions/accept": {"ref":305},
    "POST /projects/*/ai-tracking/suggestions/preview": {"ref":307},
    "POST /projects/*/ai-tracking/suggestions/generate": {"ref":310}
  },
  "nodes": [
    {"object":{"status":{"oneOf":[{"ref":1},{"literal":"degraded"},{"literal":"ok"}]}}},
    {"object":{"toString":{"ref":2},"charAt":{"ref":3},"charCodeAt":{"ref":4},"concat":{"ref":5},"indexOf":{"ref":6},"lastIndexOf":{"ref":7},"localeCompare":{"ref":8},"match":{"ref":9},"replace":{"ref":10},"search":{"ref":11},"slice":{"ref":12},"split":{"ref":13},"substring":{"ref":14},"toLowerCase":{"ref":15},"toLocaleLowerCase":{"ref":16},"toUpperCase":{"ref":17},"toLocaleUpperCase":{"ref":18},"trim":{"ref":19},"length":"number","substr":{"ref":20},"valueOf":{"ref":21},"codePointAt":{"ref":22},"includes":{"ref":23},"endsWith":{"ref":24},"normalize":{"ref":25},"repeat":{"ref":26},"startsWith":{"ref":27},"anchor":{"ref":28},"big":{"ref":29},"blink":{"ref":30},"bold":{"ref":31},"fixed":{"ref":32},"fontcolor":{"ref":33},"fontsize":{"ref":34},"italics":{"ref":35},"link":{"ref":36},"small":{"ref":37},"strike":{"ref":38},"sub":{"ref":39},"sup":{"ref":40},"padStart":{"ref":41},"padEnd":{"ref":42},"trimEnd":{"ref":43},"trimStart":{"ref":44},"trimLeft":{"ref":45},"trimRight":{"ref":46},"matchAll":{"ref":47},"replaceAll":{"ref":48},"at":{"ref":49},"__@iterator@20":{"ref":50}}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{}},
    {"object":{"status":{"oneOf":[{"ref":1},{"literal":"ok"}]}}},
    {"object":{"status":{"oneOf":[{"ref":1},{"literal":"degraded"},{"literal":"ok"}]}}},
    {"object":{"info":{"ref":54},"openapi":"string","paths":{"ref":54}}},
    {"object":{}},
    {"object":{"data":{"array":{"ref":56}}},"optional":{"apiVersions":{"array":"string"},"meta":{"ref":54}}},
    {"object":{"description":"string","input_schema":{"ref":54},"name":"string","operationId":"string"}},
    {"object":{"data":{"array":{"oneOf":[{"ref":58},{"ref":60}]}}},"optional":{"meta":{"ref":54}}},
    {"object":{"options":{"array":{"ref":59}},"pricing_model":{"literal":"flat"},"checked_at":"string","label":"string","provider_id":"string","source_url":"string"},"optional":{"notes":"string"}},
    {"object":{"key":"string","label":"string","short_label":"string","turnaround":"string","unit_cost_cents":"number","unit_cost_usd":"number"}},
    {"object":{"plans":{"array":{"ref":61}},"pricing_model":{"literal":"plan"},"checked_at":"string","label":"string","provider_id":"string","source_url":"string"},"optional":{"notes":"string"}},
    {"object":{"included_checks":"number","label":"string","monthly_price_cents":"number","monthly_price_usd":"number","plan_key":"string"}},
    {"object":{"data":{"oneOf":[{"ref":63},{"ref":65}]}},"optional":{"meta":{"ref":54}}},
    {"object":{"pricing_model":{"literal":"flat"},"selected_option":{"ref":64},"billing_units_per_check":"number","checks_per_run":"number","depth":{"oneOf":[{"literal":10},{"literal":20},{"literal":50},{"literal":100}]},"effective_cost_per_check_cents":{"oneOf":["null","number"]},"exceeds_largest_plan":"boolean","exceeds_selected_plan":"boolean","monthly_billing_units":{"oneOf":["null","number"]},"monthly_checks":{"oneOf":["null","number"]},"monthly_cost_cents":{"oneOf":["null","number"]},"monthly_cost_usd":{"oneOf":["null","number"]},"provider_id":"string","rate_checked_at":"string","rate_source_url":"string","result_pages_per_run":"number","runs_per_month":{"oneOf":["null","number"]}}},
    {"object":{"key":"string","label":"string","short_label":"string","turnaround":"string","unit_cost_cents":"number","unit_cost_usd":"number","additional_page_cost_cents":"number","additional_page_cost_usd":"number","top_100_check_cost_cents":"number","top_100_check_cost_usd":"number"}},
    {"object":{"pricing_model":{"literal":"plan"},"billing_units_per_check":"number","checks_per_run":"number","depth":{"oneOf":[{"literal":10},{"literal":20},{"literal":50},{"literal":100}]},"effective_cost_per_check_cents":{"oneOf":["null","number"]},"exceeds_largest_plan":"boolean","exceeds_selected_plan":"boolean","monthly_billing_units":{"oneOf":["null","number"]},"monthly_checks":{"oneOf":["null","number"]},"monthly_cost_cents":{"oneOf":["null","number"]},"monthly_cost_usd":{"oneOf":["null","number"]},"provider_id":"string","rate_checked_at":"string","rate_source_url":"string","result_pages_per_run":"number","runs_per_month":{"oneOf":["null","number"]}},"optional":{"selected_plan":{"ref":61}}},
    {"object":{"data":{"array":{"ref":67}},"meta":{"ref":68}}},
    {"object":{"city_name":{"oneOf":["null","string"]},"country_code":"string","display_name":"string","hl":"string","kind":{"oneOf":[{"literal":"city"},{"literal":"country"},{"literal":"region"}]},"language_code":"string","language_label":"string","location_key":"string","region_code":{"oneOf":["null","string"]},"region_name":{"oneOf":["null","string"]}}},
    {"object":{"next_cursor":{"oneOf":["null","string"]}}},
    {"object":{"email":"string","id":"string","name":"string","projects":{"array":{"ref":70}}}},
    {"object":{"domain":"string","id":"string","name":"string","role":{"oneOf":[{"literal":"admin"},{"literal":"auditor"},{"literal":"member"},{"literal":"owner"},{"literal":"viewer"}]}}},
    {"object":{"data":{"array":{"ref":72}},"meta":{"ref":68}}},
    {"object":{"created_at":"string","expires_at":{"oneOf":["null","string"]},"id":"string","last_used_at":{"oneOf":["null","string"]},"name":"string","prefix":"string","revoked_at":{"oneOf":["null","string"]},"scope":{"oneOf":[{"literal":"admin"},{"literal":"read"},{"literal":"write"}]}}},
    {"object":{"masked_value":"string","token":"string","created_at":"string","expires_at":{"oneOf":["null","string"]},"id":"string","last_used_at":{"oneOf":["null","string"]},"name":"string","prefix":"string","revoked_at":{"oneOf":["null","string"]},"scope":{"oneOf":[{"literal":"admin"},{"literal":"read"},{"literal":"write"}]}}},
    {"object":{"data":{"array":{"ref":75}},"meta":{"ref":68}}},
    {"object":{"created_at":"string","domain":"string","id":"string","name":"string","updated_at":"string","write_mode":{"oneOf":[{"literal":"active"},{"literal":"migration_hold"},{"literal":"migrated"}]}}},
    {"object":{"city":{"oneOf":["null","string"]},"country":"string","cron_expression":{"oneOf":["null","string"]},"device":{"oneOf":[{"literal":"desktop"},{"literal":"mobile"}]},"frequency":{"oneOf":[{"literal":"paused"},{"literal":"manual"},{"literal":"daily"},{"literal":"weekly"},{"literal":"monthly"},{"literal":"custom_cron"}]},"jitter_minutes":"number","last_checked_at":{"oneOf":["null","string"]},"location_key":"string","next_check_at":{"oneOf":["null","string"]},"project_id":"string","serp_depth":{"oneOf":[{"literal":10},{"literal":20},{"literal":50},{"literal":100}]},"serp_stop_on_match":"boolean","source":{"oneOf":[{"literal":"derived"},{"literal":"explicit"},{"literal":"fallback"}]},"timezone":"string","updated_at":{"oneOf":["null","string"]}}},
    {"object":{"average_position":{"oneOf":["null","number"]},"average_position_delta":{"oneOf":["null","number"]},"keywords_added_this_month":"number","last_check_at":{"oneOf":["null","string"]},"next_check_at":{"oneOf":["null","string"]},"position_distribution":{"array":{"ref":78}},"project_id":"string","top_10_count":{"oneOf":["null","number"]},"top_10_delta":{"oneOf":["null","number"]},"top_100_count":{"oneOf":["null","number"]},"top_3_count":{"oneOf":["null","number"]},"tracked_keyword_count":"number","visibility":{"oneOf":["null","number"]},"visibility_delta":{"oneOf":["null","number"]}}},
    {"object":{"count":{"oneOf":["null","number"]},"max":"number","min":"number"}},
    {"object":{"data":{"array":{"ref":80}},"meta":{"ref":82}}},
    {"object":{"keyword_id":"string","latest_position":{"oneOf":["null","number"]},"market":{"ref":81},"matched_text":"string","previous_position":{"oneOf":["null","number"]},"ranking_url":{"oneOf":["null","string"]},"text":"string"}},
    {"object":{"country_code":"string","device":{"oneOf":[{"literal":"desktop"},{"literal":"mobile"}]},"language_code":"string","language_label":"string","location":"string","location_key":"string"}},
    {"object":{"truncated_texts":{"array":"string"}}},
    {"object":{"data":{"array":{"ref":84}},"meta":{"ref":68}}},
    {"object":{"created_at":"string","expires_at":{"oneOf":["null","string"]},"id":"string","last_used_at":{"oneOf":["null","string"]},"name":"string","prefix":"string","revoked_at":{"oneOf":["null","string"]},"scope":{"oneOf":[{"literal":"admin"},{"literal":"read"},{"literal":"write"}]}}},
    {"object":{"masked_value":"string","token":"string","created_at":"string","expires_at":{"oneOf":["null","string"]},"id":"string","last_used_at":{"oneOf":["null","string"]},"name":"string","prefix":"string","revoked_at":{"oneOf":["null","string"]},"scope":{"oneOf":[{"literal":"admin"},{"literal":"read"},{"literal":"write"}]}}},
    {"object":{"data":{"array":{"ref":87}},"meta":{"ref":68}}},
    {"object":{"created_at":"string","description":{"oneOf":["null","string"]},"enabled":"boolean","id":"string","last_delivery_at":{"oneOf":["null","string"]},"updated_at":"string","url":"string"}},
    {"object":{"data":{"array":{"ref":89}},"meta":{"ref":68}}},
    {"object":{"country":"string","created_at":"string","device":{"oneOf":[{"literal":"desktop"},{"literal":"mobile"}]},"id":"string","intent":{"oneOf":["null","string"]},"language_code":"string","language_label":"string","latest_position":{"oneOf":["null","number"]},"location":"string","location_key":"string","previous_position":{"oneOf":["null","number"]},"project_id":"string","ranking_url":{"oneOf":["null","string"]},"schedule":{"oneOf":["null",{"ref":92}]},"tags":{"array":"string"},"target_url":{"oneOf":["null","string"]},"text":"string","topic":{"oneOf":["null","string"]},"updated_at":"string"},"optional":{"latest_check":{"oneOf":["null",{"ref":90}]},"latest_successful_check":{"oneOf":["null",{"ref":91}]}}},
    {"object":{"checked_at":"string","error":{"oneOf":["null","string"]},"error_code":{"oneOf":["null","string"]},"id":"string","observation_completeness":{"oneOf":["null",{"literal":"complete"},{"literal":"truncated_by_stop_on_match"},{"literal":"unknown"}]},"position":{"oneOf":["null","number"]},"run_id":{"oneOf":["null","string"]},"status":{"oneOf":[{"literal":"completed"},{"literal":"failed"},{"literal":"running"}]}}},
    {"object":{"checked_at":"string","id":"string","observation_completeness":{"oneOf":["null",{"literal":"complete"},{"literal":"truncated_by_stop_on_match"},{"literal":"unknown"}]},"position":{"oneOf":["null","number"]},"ranking_url":{"oneOf":["null","string"]},"run_id":{"oneOf":["null","string"]}}},
    {"object":{"cron_expression":{"oneOf":["null","string"]},"frequency":{"oneOf":[{"literal":"paused"},{"literal":"manual"},{"literal":"daily"},{"literal":"weekly"},{"literal":"monthly"},{"literal":"custom_cron"}]},"jitter_minutes":"number","last_checked_at":{"oneOf":["null","string"]},"next_check_at":{"oneOf":["null","string"]},"timezone":"string"}},
    {"object":{"created":"number","results":{"array":{"ref":94}},"skipped":"number"},"optional":{"warnings":{"array":"string"}}},
    {"object":{"keyword":{"ref":89},"status":{"oneOf":[{"ref":1},{"literal":"created"},{"literal":"skipped"}]}},"optional":{"warning":"string"}},
    {"object":{"operation":{"oneOf":[{"literal":"add_tags"},{"literal":"delete"},{"literal":"remove_tags"},{"literal":"set_frequency"},{"literal":"set_target_url"}]},"results":{"array":{"ref":96}}}},
    {"object":{"keyword_id":"string","status":{"oneOf":[{"ref":1},{"literal":"deleted"},{"literal":"not_found"},{"literal":"updated"}]}}},
    {"object":{"cached":"boolean","connections":{"array":{"ref":98}},"cost_cents":"number","fetched_at":"string","offset":"number","rows":{"array":{"ref":99}},"total_count":{"oneOf":["null","number"]}}},
    {"object":{"id":"string","label":"string","provider":{"literal":"dataforseo"}}},
    {"object":{"already_tracked":"boolean","estimated_traffic":{"oneOf":["null","number"]},"keyword":"string","position":{"oneOf":["null","number"]},"search_volume":{"oneOf":["null","number"]}}},
    {"object":{"cached":"boolean","connections":{"array":{"ref":101}},"cost_cents":"number","estimate":{"literal":true},"provider":"string","sources":{"array":{"ref":102}}}},
    {"object":{"id":"string","label":"string","provider":"string"}},
    {"object":{"cached":"boolean","cost_cents":"number","source":{"oneOf":[{"literal":"related"},{"literal":"suggestion"},{"literal":"idea"}]}}},
    {"object":{"cached":"boolean","connections":{"array":{"ref":101}},"cost_cents":"number","fetched_at":"string","provider":"string","rows":{"array":{"ref":104}},"sources":{"array":{"ref":106}},"total_count":"number"},"optional":{"estimate":"unknown"}},
    {"object":{"already_tracked":"boolean","source":{"oneOf":[{"literal":"related"},{"literal":"suggestion"},{"literal":"idea"}]},"keyword":"string","competition":{"oneOf":["null","number"]},"cpc_cents":{"oneOf":["null","number"]},"difficulty":{"oneOf":["null","number"]},"intent":{"oneOf":["null",{"literal":"unknown"},{"literal":"informational"},{"literal":"commercial"},{"literal":"transactional"},{"literal":"navigational"}]},"monthly_trend":{"array":{"ref":105}},"search_volume":{"oneOf":["null","number"]}}},
    {"object":{"month":"number","search_volume":{"oneOf":["null","number"]},"year":"number"}},
    {"object":{"cached":"boolean","cost_cents":"number","returned":"number","source":{"oneOf":[{"literal":"related"},{"literal":"suggestion"},{"literal":"idea"}]},"status":{"oneOf":[{"literal":"ok"},{"literal":"failed"},{"literal":"skipped"}]}},"optional":{"reason":{"oneOf":[{"literal":"budget_exhausted"},{"literal":"cost_limit"},{"literal":"in_progress"},{"literal":"needs_reauth"},{"literal":"no_source"},{"literal":"previous_source_failed"},{"literal":"provider_error"},{"literal":"rate_limited"},{"literal":"result_limit"},{"literal":"unsupported_location"}]}}},
    {"object":{"data":{"oneOf":[{"ref":108},{"ref":109}]}},"optional":{"meta":{"ref":54}}},
    {"object":{"cached":"boolean","cached_until":{"oneOf":["null","string"]},"cost_cents":"number","estimate":{"literal":true},"estimated_cost_cents":"number","include_subdomains":"boolean","provider":"string","target":"string","target_scope":{"oneOf":[{"literal":"site"},{"literal":"page"}]}}},
    {"object":{"cached":"boolean","cached_until":"string","cost_cents":"number","fetched_at":"string","fetched_row_count":"number","history":{"array":{"ref":110}},"include_subdomains":"boolean","provider":"string","rows":{"array":{"ref":111}},"summary":{"ref":112},"target":"string","target_scope":{"oneOf":[{"literal":"site"},{"literal":"page"}]},"total_rows_available":"number"},"optional":{"estimate":"unknown","history_unavailable":"boolean"}},
    {"object":{"lost_links":"number","month":"string","new_links":"number"}},
    {"object":{"anchor":"string","domain_authority":"number","first_seen":"string","flags":{"array":{"oneOf":[{"literal":"nofollow"},{"literal":"ugc"},{"literal":"sponsored"},{"literal":"image"},{"literal":"sitewide"}]}},"links_count":"number","lost_at":{"oneOf":["null","string"]},"source_domain":"string","source_url":"string","spam_score":"number","status":{"oneOf":[{"literal":"active"},{"literal":"new"},{"literal":"lost"}]},"target_url":"string"}},
    {"object":{"backlinks_total":"number","broken_backlinks":"number","broken_pages":"number","dofollow_pct":"number","domain_rank":"number","lost_backlinks":"number","lost_referring_domains":"number","new_backlinks":"number","new_referring_domains":"number","referring_domains_total":"number","referring_pages":"number","spam_score":"number"}},
    {"object":{"data":{"ref":109}},"optional":{"meta":{"ref":54}}},
    {"object":{"data":{"oneOf":[{"ref":115},{"ref":116}]}},"optional":{"meta":{"ref":54}}},
    {"object":{"cached":"boolean","estimate":{"literal":true},"estimated_cost_cents":"number","fresh_estimated_cost_cents":"number","history_estimated_cost_cents":"number","history_mode":{"literal":"lazy"},"keyword_page_estimated_cost_cents":"number","language_code":"string","location_code":"number","page_page_estimated_cost_cents":"number","provider":"string","scope":{"oneOf":[{"literal":"root"},{"literal":"subdomain"}]},"target":"string"}},
    {"object":{"cached":"boolean","cached_until":"string","cost_cents":"number","fetched_at":"string","history_mode":{"literal":"lazy"},"keywords":{"oneOf":[{"ref":117},{"ref":118}]},"language_code":"string","location_code":"number","overview":{"oneOf":["null",{"ref":121}]},"pages":{"oneOf":[{"ref":117},{"ref":122}]},"previous_fetched_at":{"oneOf":["null","string"]},"previous_overview":{"oneOf":["null",{"ref":121}]},"previous_source_snapshot_at":{"oneOf":["null","string"]},"provider":"string","scope":{"oneOf":[{"literal":"root"},{"literal":"subdomain"}]},"source_snapshot_at":{"oneOf":["null","string"]},"state":{"oneOf":[{"literal":"ok"},{"literal":"no_data"},{"literal":"partial"}]},"target":"string"}},
    {"object":{"cost_cents":"number","ok":{"literal":false},"reason":{"oneOf":[{"literal":"budget_exhausted"},{"literal":"in_progress"},{"literal":"needs_reauth"},{"literal":"no_source"},{"literal":"rate_limited"},{"literal":"unsupported_location"},{"literal":"cost_limit_exceeded"},{"literal":"lookup_failed"},{"literal":"snapshot_expired"}]}},"optional":{"reset_at":"number"}},
    {"object":{"cached":"boolean","cost_cents":"number","data":{"ref":119},"fetched_at":"string","ok":{"literal":true}}},
    {"object":{"cost_cents":"number","rows":{"array":{"ref":120}},"total_count":{"oneOf":["null","number"]}}},
    {"object":{"cpc_cents":{"oneOf":["null","number"]},"difficulty":{"oneOf":["null","number"]},"estimated_traffic":{"oneOf":["null","number"]},"intent":{"oneOf":["null",{"literal":"informational"},{"literal":"commercial"},{"literal":"transactional"},{"literal":"navigational"}]},"keyword":"string","position":{"oneOf":["null","number"]},"rank_absolute":{"oneOf":["null","number"]},"rank_absolute_delta":{"oneOf":["null","number"]},"ranking_url":{"oneOf":["null","string"]},"search_volume":{"oneOf":["null","number"]},"serp_features":{"array":"string"}}},
    {"object":{"count":{"oneOf":["null","number"]},"estimated_traffic_cost_cents":{"oneOf":["null","number"]},"etv":{"oneOf":["null","number"]},"is_down":"number","is_lost":"number","is_new":"number","is_up":"number","pos1":"number","pos11_20":"number","pos21_30":"number","pos2_3":"number","pos31_40":"number","pos41_50":"number","pos4_10":"number","pos51_60":"number","pos61_70":"number","pos71_80":"number","pos81_90":"number","pos91_100":"number"}},
    {"object":{"cached":"boolean","cost_cents":"number","data":{"ref":123},"fetched_at":"string","ok":{"literal":true}}},
    {"object":{"cost_cents":"number","rows":{"array":{"ref":124}},"total_count":"number"}},
    {"object":{"etv":{"oneOf":["null","number"]},"etv_delta_pct":{"oneOf":["null","number"]},"keyword_count":{"oneOf":["null","number"]},"path":"string","top_keyword":{"oneOf":["null","string"]},"top_keyword_position":{"oneOf":["null","number"]}}},
    {"object":{"data":{"ref":126}},"optional":{"meta":{"ref":54}}},
    {"object":{"cached":"boolean","cost_cents":"number","data":{"array":{"ref":127}},"fetched_at":"string"}},
    {"object":{"metrics":{"ref":121},"month":"number","year":"number"}},
    {"object":{"data":{"ref":129}},"optional":{"meta":{"ref":54}}},
    {"object":{"cached":"boolean","cost_cents":"number","data":{"ref":119},"fetched_at":"string"}},
    {"object":{"data":{"ref":131}},"optional":{"meta":{"ref":54}}},
    {"object":{"cached":"boolean","cost_cents":"number","data":{"ref":123},"fetched_at":"string"}},
    {"object":{"cached_count":"number","connections":{"array":{"ref":101}},"cost_cents":"number","fetched_at":"string","fetched_count":"number","provider":"string","rows":{"array":{"ref":133}},"total_count":"number"},"optional":{"estimate":"boolean","estimated_cost_cents":"number","fetched_count_estimate":"number"}},
    {"object":{"keyword":"string","competition":{"oneOf":["null","number"]},"cpc_cents":{"oneOf":["null","number"]},"difficulty":{"oneOf":["null","number"]},"intent":{"oneOf":["null",{"literal":"unknown"},{"literal":"informational"},{"literal":"commercial"},{"literal":"transactional"},{"literal":"navigational"}]},"monthly_trend":{"array":{"ref":105}},"search_volume":{"oneOf":["null","number"]}}},
    {"object":{"data":{"array":{"ref":135}},"meta":{"ref":68}}},
    {"object":{"checked_at":"string","id":"string","keyword":"string","keyword_id":"string","position":{"oneOf":["null","number"]},"previous_position":{"oneOf":["null","number"]},"ranking_url":{"oneOf":["null","string"]}}},
    {"object":{"data":{"array":{"ref":137}},"meta":{"ref":68}}},
    {"object":{"enabled":"boolean","id":"string","latest_snapshot":{"oneOf":["null",{"ref":138}]},"project_id":"string","sitemap_url":{"oneOf":["null","string"]},"status":{"oneOf":[{"literal":"active"},{"literal":"disabled"},{"literal":"pending"}]}}},
    {"object":{"fetched_at":"string","sitemap_url":"string","url_count":"number"}},
    {"object":{"data":{"array":{"ref":140}},"meta":{"ref":68}}},
    {"object":{"attempts":{"oneOf":["null",{"array":{"ref":141}}]},"checked_at":"string","cost_cents":{"oneOf":["null","number"]},"error":{"oneOf":["null","string"]},"id":"string","keyword_id":"string","position":{"oneOf":["null","number"]},"previous_position":{"oneOf":["null","number"]},"provider":"string","ranking_url":{"oneOf":["null","string"]},"run_id":{"oneOf":["null","string"]},"status":{"oneOf":[{"literal":"completed"},{"literal":"failed"},{"literal":"running"}]}},"optional":{"observation_completeness":{"oneOf":["null",{"literal":"complete"},{"literal":"truncated_by_stop_on_match"},{"literal":"unknown"}]}}},
    {"object":{"message":"string","provider":"string"}},
    {"object":{"id":"string","status":{"literal":"queued"}}},
    {"object":{"created_at":"string","happened_at":"string","id":"string","keyword_id":{"oneOf":["null","string"]},"payload":{"oneOf":["null",{"ref":54}]},"project_id":"string","public_id":"string","severity":{"oneOf":[{"literal":"critical"},{"literal":"info"},{"literal":"warning"}]},"source":{"oneOf":[{"literal":"manual"},{"literal":"api"},{"literal":"cms"},{"literal":"deploy"},{"literal":"rank_tracker"},{"literal":"search_analytics"},{"literal":"search_engine_status"},{"literal":"sitemap"},{"literal":"url_inspection"}]},"type":"string","url":{"oneOf":["null","string"]}}},
    {"object":{"data":{"array":{"ref":143}},"meta":{"ref":68}}},
    {"object":{"offset":"number","rows":{"array":{"ref":146}},"total_count":"number"}},
    {"object":{"bounce_rate":{"oneOf":["null","number"]},"created_at":"string","date":"string","engagement_rate":{"oneOf":["null","number"]},"key_events":{"oneOf":["null","number"]},"path":"string","provider":"string","scroll_depth":{"oneOf":["null","number"]},"sessions":"number","updated_at":"string","visit_duration_seconds":{"oneOf":["null","number"]},"visitors":{"oneOf":["null","number"]},"window_days":"number"}},
    {"object":{"connection":{"ref":148},"rows":{"array":{"ref":149}}}},
    {"object":{"id":"string","label":"string","provider":"string"}},
    {"object":{"clicks":"number","ctr":"number","impressions":"number","position":"number","query":"string"},"optional":{"page":{"oneOf":["null","string"]}}},
    {"object":{"connections":"number","keyword_snapshots":"number","page_snapshots":"number","project_id":"string","runs":{"array":{"ref":151}},"skipped":{"array":{"ref":152}}}},
    {"object":{"connection_id":"string","provider":"string","rows_fetched":"number","rows_matched":"number","rows_upserted":"number","status":{"oneOf":[{"literal":"failed"},{"literal":"succeeded_with_data"},{"literal":"succeeded_empty"},{"literal":"deferred_rate_limit"},{"literal":"not_applicable"}]},"truncated":"boolean"},"optional":{"error":"string","error_class":"string"}},
    {"object":{"provider":"string","reason":{"oneOf":[{"literal":"rate_limited"},{"literal":"no_capability"}]}}},
    {"object":{"data":{"array":{"oneOf":[{"ref":154},{"ref":155},{"ref":156}]}},"meta":{"ref":68}}},
    {"object":{"channels":{"array":{"oneOf":[{"literal":"email"},{"literal":"slack"},{"literal":"webhook"}]}},"condition_type":{"oneOf":[{"literal":"change_pct"},{"literal":"competitor_overtake"},{"literal":"ctr_drop"},{"literal":"downtrend"},{"literal":"enters_top_n"},{"literal":"exits_top_n"},{"literal":"position_drop"},{"literal":"serp_feature"},{"literal":"threshold"},{"literal":"url_mismatch"}]},"enabled":"boolean","id":"string","name":"string","recipient_ids":{"array":"string"},"target_ids":{"array":"string"},"target_type":{"literal":"keyword"}},"optional":{"change_pct":{"oneOf":["null","string","number"]},"channel":"string","condition":"string","competitor_domain":{"oneOf":["null","string"]},"created_at":"string","fires":"string","period":"string","scope":"string","serp_feature":{"oneOf":["null","string"]},"severity":{"oneOf":[{"literal":"info"},{"literal":"warning"},{"literal":"urgent"}]},"status":{"oneOf":[{"ref":1},{"literal":"active"},{"literal":"paused"}]},"threshold_position":{"oneOf":["null","number"]},"top_n":{"oneOf":["null","number"]},"updated_at":"string"}},
    {"object":{"channels":{"array":{"oneOf":[{"literal":"email"},{"literal":"slack"},{"literal":"webhook"}]}},"condition_type":{"oneOf":[{"literal":"change_pct"},{"literal":"competitor_overtake"},{"literal":"ctr_drop"},{"literal":"downtrend"},{"literal":"enters_top_n"},{"literal":"exits_top_n"},{"literal":"position_drop"},{"literal":"serp_feature"},{"literal":"threshold"},{"literal":"url_mismatch"}]},"enabled":"boolean","id":"string","name":"string","recipient_ids":{"array":"string"},"target_ids":{"array":"string"},"target_type":{"literal":"tag"}},"optional":{"change_pct":{"oneOf":["null","string","number"]},"channel":"string","condition":"string","competitor_domain":{"oneOf":["null","string"]},"created_at":"string","fires":"string","period":"string","scope":"string","serp_feature":{"oneOf":["null","string"]},"severity":{"oneOf":[{"literal":"info"},{"literal":"warning"},{"literal":"urgent"}]},"status":{"oneOf":[{"ref":1},{"literal":"active"},{"literal":"paused"}]},"threshold_position":{"oneOf":["null","number"]},"top_n":{"oneOf":["null","number"]},"updated_at":"string"}},
    {"object":{"channels":{"array":{"oneOf":[{"literal":"email"},{"literal":"slack"},{"literal":"webhook"}]}},"condition_type":{"oneOf":[{"literal":"change_pct"},{"literal":"competitor_overtake"},{"literal":"ctr_drop"},{"literal":"downtrend"},{"literal":"enters_top_n"},{"literal":"exits_top_n"},{"literal":"position_drop"},{"literal":"serp_feature"},{"literal":"threshold"},{"literal":"url_mismatch"}]},"enabled":"boolean","id":"string","name":"string","recipient_ids":{"array":"string"},"target_ids":{"emptyArray":true},"target_type":{"literal":"all"}},"optional":{"change_pct":{"oneOf":["null","string","number"]},"channel":"string","condition":"string","competitor_domain":{"oneOf":["null","string"]},"created_at":"string","fires":"string","period":"string","scope":"string","serp_feature":{"oneOf":["null","string"]},"severity":{"oneOf":[{"literal":"info"},{"literal":"warning"},{"literal":"urgent"}]},"status":{"oneOf":[{"ref":1},{"literal":"active"},{"literal":"paused"}]},"threshold_position":{"oneOf":["null","number"]},"top_n":{"oneOf":["null","number"]},"updated_at":"string"}},
    {"object":{"deleted":"boolean"}},
    {"object":{"data":{"array":{"ref":159}},"meta":{"ref":68}}},
    {"object":{"action":"string","ctas":{"array":"string"},"current":"string","headline":"string","id":"string","keyword":"string","previous":"string","rule":"string","severity":{"oneOf":[{"literal":"info"},{"literal":"warning"},{"literal":"urgent"}]},"unread":"boolean","when":"string"}},
    {"object":{"muted":{"literal":true},"snoozed_until":{"oneOf":["null","string"]}}},
    {"object":{"updated":"number"}},
    {"object":{"data":{"array":{"ref":163}},"meta":{"ref":68}}},
    {"object":{"color":{"oneOf":[{"ref":1},{"literal":"accent"},{"literal":"blue"},{"literal":"purple"}]},"email":"string","id":"string","initials":"string","name":"string","role":{"oneOf":[{"literal":"Admin"},{"literal":"Editor"},{"literal":"Owner"},{"literal":"Viewer"}]},"role_value":{"oneOf":[{"literal":"admin"},{"literal":"member"},{"literal":"owner"},{"literal":"viewer"}]}}},
    {"object":{"data":{"array":{"ref":165}},"meta":{"ref":68}}},
    {"object":{"email":"string","expires_label":"string","id":"string","invited_label":"string","role":{"oneOf":[{"literal":"Admin"},{"literal":"Editor"},{"literal":"Owner"},{"literal":"Viewer"}]},"role_value":{"oneOf":[{"literal":"admin"},{"literal":"member"},{"literal":"viewer"}]}}},
    {"object":{"expires_at":"string","id":"string","invite_link":"string"}},
    {"object":{"id":"string"}},
    {"object":{"expires_at":"string","id":"string","invite_link":"string"}},
    {"object":{"id":"string","role":{"oneOf":[{"literal":"admin"},{"literal":"member"},{"literal":"viewer"}]}}},
    {"object":{"id":"string"}},
    {"object":{"data":{"ref":172}},"optional":{"meta":{"ref":54}}},
    {"object":{"models":{"array":{"ref":173}},"visibility_markets":{"array":{"ref":174}},"response_countries":{"array":{"ref":176}},"response_languages":{"array":{"ref":177}},"limits":{"ref":178},"fetched_at":"string"},"optional":{"actual_cost_available":"boolean"}},
    {"object":{"id":"string","provider":{"literal":"chat_gpt"},"label":"string","reasoning":"boolean","web_search":"boolean","min_output_tokens":"number","max_output_tokens":"number","price_available":"boolean","admission_enabled":"boolean","actual_cost_enabled":"boolean"}},
    {"object":{"platform":{"oneOf":[{"literal":"chat_gpt"},{"literal":"google"}]},"location_code":"number","country_name":"string","languages":{"array":{"ref":175}}}},
    {"object":{"code":"string","name":"string"}},
    {"object":{"code":"string","name":"string"}},
    {"object":{"code":"string","name":"string"}},
    {"object":{"max_models":{"literal":2},"max_output_tokens":{"literal":4096}}},
    {"object":{"data":{"ref":180}},"optional":{"meta":{"ref":54}}},
    {"object":{"updated_at":{"oneOf":["null","string"]},"business":"string","audience":"string","products":"string","goals":"string","agent_rules":"string"}},
    {"object":{"data":{"array":{"ref":182}},"meta":{"ref":68}}},
    {"object":{"id":"string","title":"string","kind":"string","created_at":"string"}},
    {"object":{"data":{"ref":184}},"optional":{"meta":{"ref":54}}},
    {"object":{"body":{"ref":185},"provenance":{"ref":185},"id":"string","title":"string","kind":"string","created_at":"string"}},
    {"object":{}},
    {"object":{"data":{"oneOf":[{"ref":187},{"ref":188}]}},"optional":{"meta":{"ref":54}}},
    {"object":{"ok":{"literal":true},"estimate":{"literal":true},"estimated_cost_cents":"number","evidence":{"oneOf":[{"literal":"observed_dataset"},{"literal":"synthetic_prompt_test"}]}},"optional":{"estimate_kind":{"oneOf":[{"literal":"forecast"},{"literal":"admission_bound"}]},"is_guaranteed_maximum":"boolean","credential_source":{"oneOf":[{"literal":"own"},{"literal":"hosted"}]},"estimate_credentials_ref":"string","is_partial_estimate":"boolean","pricing_policy":{"oneOf":[{"literal":"legacy_dated"},{"literal":"current_catalog"},{"literal":"provider_actual_cost"}]},"pricing_checked_at":"string","forecast_exclusions":{"array":"string"},"forecast_scope":{"literal":"tokens_and_base_only"},"forecast_assumptions":{"array":"string"}}},
    {"object":{"ok":{"literal":true},"estimate":{"literal":false},"cached":"boolean","report_id":"string","cost_cents":"number","result":{"ref":189}},"optional":{"retry_blocked":"boolean"}},
    {"object":{"evidence":{"oneOf":[{"literal":"observed_dataset"},{"literal":"synthetic_prompt_test"}]},"rows":{"array":{"ref":190}},"total_available":{"oneOf":["null","number"]},"truncated":"boolean","fetched_at":"string","cost_cents":"number","cost_status":{"oneOf":[{"literal":"unknown"},{"literal":"confirmed"}]},"failure":{"oneOf":["null","string"]}}},
    {"object":{"prompt":"string","model":"string","answer":"string","observed_at":{"oneOf":["null","string"]},"brand_mentioned":"boolean","domain_cited":"boolean","citations":{"array":{"ref":191}}},"optional":{"content_truncated":"boolean"}},
    {"object":{"title":"string","url":"string","target_domain":"boolean"}},
    {"object":{"data":{"array":{"ref":182}}},"optional":{"meta":{"ref":54}}},
    {"object":{"data":{"ref":194}},"optional":{"meta":{"ref":54}}},
    {"object":{"id":"string","created_at":"string","cached":"boolean","result":{"ref":195}}},
    {"object":{"version":{"literal":1},"target":"string","started_at":"string","completed_at":"string","state":{"oneOf":[{"literal":"complete"},{"literal":"partial"}]},"stop_reason":{"oneOf":[{"literal":"finished"},{"literal":"page_limit"},{"literal":"time_limit"},{"literal":"request_limit"}]},"limits":{"ref":196},"requests":"number","pages":{"array":{"ref":197}},"summary":{"ref":200},"limitations":{"array":"string"}}},
    {"object":{"max_pages":"number","max_requests":"number","max_duration_ms":"number","max_page_bytes":"number"}},
    {"object":{"url":"string","final_url":"string","status":{"oneOf":["null","number"]},"response_time_ms":"number","title":{"oneOf":["null","string"]},"description":{"oneOf":["null","string"]},"canonical":{"oneOf":["null","string"]},"headings":{"array":{"ref":198}},"h1_count":"number","indexable":"boolean","robots":{"oneOf":["null","string"]},"internal_link_count":"number","external_link_count":"number","internal_links":{"array":"string"},"image_count":"number","missing_alt_count":"number","issues":{"array":{"ref":199}}}},
    {"object":{"level":"number","text":"string"}},
    {"object":{"code":"string","severity":{"oneOf":[{"literal":"info"},{"literal":"warning"},{"literal":"error"}]},"message":"string"}},
    {"object":{"pages":"number","errors":"number","warnings":"number","indexable":"number"}},
    {"object":{"data":{"array":{"ref":202}},"meta":{"ref":203}}},
    {"object":{"fresh_until":"string","kind":{"oneOf":[{"literal":"backlinks"},{"literal":"domain_overview"},{"literal":"keyword_research"}]},"saved_at":"string","state":{"oneOf":[{"literal":"fresh"},{"literal":"stale"}]}},"optional":{"country_code":"string","include_clickstream":"boolean","include_subdomains":"boolean","language_code":"string","location_code":"number","mode":"string","result_limit":"number","seed":"string","target":"string","target_scope":"string"}},
    {"object":{"freshness_days":"number"}},
    {"object":{"data":{"oneOf":[{"ref":205},{"ref":206},{"ref":207}]}}},
    {"object":{"cached":"boolean","cached_until":"string","cost_cents":"number","fetched_at":"string","fetched_row_count":"number","history":{"array":{"ref":110}},"include_subdomains":"boolean","provider":"string","rows":{"array":{"ref":111}},"summary":{"ref":112},"target":"string","target_scope":{"oneOf":[{"literal":"site"},{"literal":"page"}]},"total_rows_available":"number","fresh_until":"string","saved_at":"string","stale":"boolean","state":{"oneOf":[{"literal":"fresh"},{"literal":"stale"}]}},"optional":{"estimate":"unknown","history_unavailable":"boolean"}},
    {"object":{"cached":"boolean","cost_cents":"number","country_code":{"oneOf":["null","string"]},"data_state":{"oneOf":[{"literal":"ok"},{"literal":"no_data"},{"literal":"partial"}]},"fetched_at":"string","fresh_until":"string","history":{"oneOf":["null",{"array":{"ref":127}}]},"keywords":{"oneOf":["null",{"ref":119}]},"language_code":"string","location_code":"number","overview":{"oneOf":["null",{"ref":121}]},"pages":{"oneOf":["null",{"ref":123}]},"partial":"boolean","previous_fetched_at":{"oneOf":["null","string"]},"previous_overview":{"oneOf":["null",{"ref":121}]},"previous_source_snapshot_at":{"oneOf":["null","string"]},"provider":"string","saved_at":"string","scope":{"oneOf":[{"literal":"root"},{"literal":"subdomain"}]},"source_snapshot_at":{"oneOf":["null","string"]},"stale":"boolean","state":{"oneOf":[{"literal":"fresh"},{"literal":"stale"}]},"target":"string"}},
    {"object":{"cached":"boolean","cost_cents":"number","country_code":"string","fetched_at":"string","fresh_until":"string","include_clickstream":"boolean","language_code":"string","mode":"string","partial":"boolean","provider":"string","request_key":"string","result_limit":"number","rows":{"array":{"ref":208}},"saved_at":"string","seed":"string","sources":{"array":{"ref":210}},"stale":"boolean","state":{"oneOf":[{"literal":"fresh"},{"literal":"stale"}]}}},
    {"object":{"already_saved":"boolean","already_tracked":"boolean","competition":{"oneOf":["null","number"]},"cpc_cents":{"oneOf":["null","number"]},"difficulty":{"oneOf":["null","number"]},"intent":{"oneOf":["null",{"literal":"unknown"},{"literal":"informational"},{"literal":"commercial"},{"literal":"transactional"},{"literal":"navigational"}]},"keyword":"string","monthly_trend":{"array":{"ref":209}},"search_volume":{"oneOf":["null","number"]},"source":{"oneOf":[{"literal":"related"},{"literal":"suggestion"},{"literal":"idea"}]}}},
    {"object":{"month":"number","search_volume":{"oneOf":["null","number"]},"year":"number"}},
    {"object":{"cached":"boolean","cost_cents":"number","returned":"number","source":{"oneOf":[{"literal":"related"},{"literal":"suggestion"},{"literal":"idea"}]},"status":{"oneOf":[{"literal":"ok"},{"literal":"failed"},{"literal":"skipped"}]}},"optional":{"reason":{"oneOf":[{"literal":"budget_exhausted"},{"literal":"cost_limit"},{"literal":"in_progress"},{"literal":"needs_reauth"},{"literal":"no_source"},{"literal":"previous_source_failed"},{"literal":"provider_error"},{"literal":"rate_limited"},{"literal":"result_limit"},{"literal":"unsupported_location"}]}}},
    {"object":{"data":{"array":{"ref":212}},"meta":{"ref":68}}},
    {"object":{"connection_id":"string","credential_source":{"oneOf":[{"literal":"own"},{"literal":"hosted"}]},"credits":{"ref":213},"own":{"ref":216},"provider":"string","source":{"oneOf":[{"literal":"connection"},{"literal":"legacy_project"},{"literal":"none"}]}}},
    {"object":{"app":{"oneOf":["null",{"ref":214}]},"programmatic":{"oneOf":["null",{"ref":215}]}}},
    {"object":{"amount_per_month":"number","unit":{"literal":"cents"}}},
    {"object":{"amount_per_month":"number","unit":{"literal":"cents"}}},
    {"object":{"app":{"oneOf":["null",{"ref":217}]},"programmatic":{"oneOf":["null",{"ref":218}]}}},
    {"object":{"amount_per_month":"number","unit":{"oneOf":[{"literal":"cents"},{"literal":"units"}]}}},
    {"object":{"amount_per_month":"number","unit":{"oneOf":[{"literal":"cents"},{"literal":"units"}]}}},
    {"object":{"data":{"array":{"ref":220}},"meta":{"ref":68}}},
    {"object":{"category_id":"string","category_title":"string","description":"string","drawer":{"ref":221},"icon":{"oneOf":[{"literal":"chart"},{"literal":"database"},{"literal":"globe"},{"literal":"link"},{"literal":"magnifier"},{"literal":"table"},{"literal":"trend"}]},"id":{"oneOf":[{"ref":1},{"literal":"dataforseo"},{"literal":"ga4"},{"literal":"gsc"},{"literal":"plausible"},{"literal":"serpapi"}]},"meta":{"array":{"ref":222}},"name":"string","status":{"oneOf":[{"ref":1},{"literal":"connected"},{"literal":"optional"},{"literal":"planned"},{"literal":"ready"}]},"tint":"string"},"optional":{"enabled":"boolean","logo_domain":"string","primary":"boolean","priority":"number","secondary_action":"string"}},
    {"object":{"activities":{"array":{"ref":222}},"cost_help":"string","credential_fields":{"array":{"ref":223}},"defaults":{"ref":224},"env_hint":"string","primary_toggle_label":"string"}},
    {"object":{"label":"string","value":"string"}},
    {"object":{"label":"string","name":{"oneOf":[{"ref":1},{"literal":"login"},{"literal":"secret"}]},"placeholder":"string"},"optional":{"type":{"oneOf":[{"ref":1},{"literal":"password"},{"literal":"text"}]}}},
    {"object":{"cost_per_check":"number","depth":"string","device":"string","language":"string","location":"string","login":"string","primary":"boolean","secret":"string"},"optional":{"enabled":"boolean","priority":"number"}},
    {"object":{"cost_per_check_cents":{"oneOf":["null","string","number"]},"created_at":"string","enabled":"boolean","id":"string","is_primary":"boolean","kind":{"oneOf":[{"literal":"analytics"},{"literal":"enrichment"},{"literal":"serp"}]},"last_used_at":{"oneOf":["null","string"]},"priority":"number","project_id":"string","provider":{"oneOf":[{"ref":1},{"literal":"dataforseo"},{"literal":"ga4"},{"literal":"gsc"},{"literal":"plausible"},{"literal":"serpapi"}]},"status":{"oneOf":[{"ref":1},{"literal":"connected"},{"literal":"optional"},{"literal":"planned"},{"literal":"ready"}]},"updated_at":"string"},"optional":{"credentials_hash":{"oneOf":["null","string"]}}},
    {"object":{"message":"string","ok":"boolean"},"optional":{"balance":"number"}},
    {"object":{"ok":"boolean"}},
    {"object":{"data":{"array":{"ref":229}},"meta":{"ref":68}}},
    {"object":{"config":{"oneOf":[{"ref":230},{"ref":233}]},"created_at":"string","created_by_id":{"oneOf":["null","string"]},"id":"string","name":"string","surface":{"oneOf":[{"literal":"competitors"},{"literal":"keywords"}]}}},
    {"object":{"filters":{"ref":231},"scope":{"ref":232},"surface":{"literal":"competitors"},"version":{"literal":1}}},
    {"object":{"excluded_keyword_ids":{"array":"string"},"position":{"oneOf":[{"literal":"all"},{"literal":"top10"},{"literal":"top3"}]},"tag":{"oneOf":["null","string"]}}},
    {"object":{"device":{"oneOf":[{"literal":"desktop"},{"literal":"mobile"}]},"engine":{"literal":"google"},"location_id":"string"}},
    {"object":{"filters":{"ref":234},"lens":{"ref":235},"search":"string","surface":{"literal":"keywords"},"version":{"literal":1}}},
    {"object":{"change":{"oneOf":[{"literal":"new"},{"literal":"lost"},{"literal":"any"},{"literal":"down"},{"literal":"up"}]},"contains":"string","intents":{"array":"string"},"last_check":{"oneOf":[{"literal":"completed"},{"literal":"failed"},{"literal":"running"},{"literal":"any"}]},"position":{"array":{"oneOf":[{"literal":"top10"},{"literal":"top3"},{"literal":"11-50"},{"literal":"51-100"}]}},"serp":{"array":{"oneOf":[{"literal":"image"},{"literal":"ai"},{"literal":"featured"},{"literal":"paa"},{"literal":"sitelinks"},{"literal":"video"}]}},"tags":{"array":"string"},"topics":{"array":"string"},"url_changed":"boolean","vol_max":"number","vol_min":"number","wrong_url":"boolean"}},
    {"object":{"device":{"oneOf":[{"literal":"desktop"},{"literal":"mobile"},{"literal":"all"}]},"location_id":{"oneOf":["null","string"]}}},
    {"object":{"deleted":"boolean"}},
    {"object":{"data":{"array":{"ref":238}},"meta":{"ref":68}}},
    {"object":{"cpc":{"oneOf":["null","number"]},"difficulty":{"oneOf":["null","number"]},"id":"string","intent":{"oneOf":["null","string"]},"location":"string","saved_at":"string","source_seed":{"oneOf":["null","string"]},"text":"string","trend":{"array":{"ref":239}},"variant_count":"number","volume":{"oneOf":["null","number"]}}},
    {"object":{"month":"number","search_volume":{"oneOf":["null","number"]},"year":"number"}},
    {"object":{"duplicate_count":"number","results":{"array":{"ref":241}},"saved_count":"number"}},
    {"object":{"keyword":"string","status":{"oneOf":[{"literal":"created"},{"literal":"skipped"}]}}},
    {"object":{"removed_count":"number"}},
    {"object":{"meta":{"ref":244},"data":{"array":{"ref":251}}}},
    {"object":{"markets":{"array":{"ref":245}},"suggestions":{"array":{"ref":250}},"next_cursor":{"oneOf":["null","string"]}}},
    {"object":{"checked_keyword_count":"number","columns":{"array":{"ref":246}},"competitor_count":"number","country":"string","device":"string","engine":"string","has_rank_data":"boolean","key":"string","rows":{"array":{"ref":247}},"shares":{"array":{"ref":249}},"shared_keyword_count":"number","tracked_keyword_count":"number"}},
    {"object":{"domain":"string","kind":{"oneOf":[{"literal":"Managed"},{"literal":"You"}]},"label":"string"},"optional":{"id":"string"}},
    {"object":{"gap":{"oneOf":["null","number"]},"keyword":"string","ranks":{"ref":248}}},
    {"object":{},"optional":{"you":{"oneOf":["null","number"]}}},
    {"object":{"color":"string","domain":"string","initials":"string","kind":{"oneOf":[{"literal":"Managed"},{"literal":"You"}]},"label":"string","share_of_voice":"number","shared_keywords":"number"},"optional":{"id":"string"}},
    {"object":{"domain":"string","initials":"string","overlap":"number"}},
    {"object":{"domain":"string","id":"string","label":{"oneOf":["null","string"]}},"optional":{"initials":"string"}},
    {"object":{"removed":"boolean"}},
    {"object":{"alert_email":"boolean","alert_in_app":"boolean","alert_slack":"boolean","alert_webhook":"boolean","check_email":"boolean","check_in_app":"boolean","import_email":"boolean","import_in_app":"boolean","invite_email":"boolean","invite_in_app":"boolean","project_id":"string"},"optional":{"email":"string","email_verification":{"oneOf":[{"literal":"unverified"},{"literal":"verified"}]},"slack_available":"boolean","webhook_available":"boolean"}},
    {"object":{"meta":{"ref":255},"data":{"array":{"ref":257}}}},
    {"object":{"import_job":{"ref":256},"next_cursor":{"oneOf":["null","string"]}}},
    {"object":{"counts":"unknown","created_at":{"oneOf":["null","string"]},"error":{"oneOf":["null","string"]},"finished_at":{"oneOf":["null","string"]},"id":{"oneOf":["null","string"]},"progress":"number","started_at":{"oneOf":["null","string"]},"state":{"oneOf":[{"literal":"failed"},{"literal":"done"},{"literal":"idle"},{"literal":"importing"},{"literal":"receiving"}]}}},
    {"object":{"created_at":"string","expires_at":"string","id":"string","scope":{"oneOf":[{"literal":"keywords"},{"literal":"full"}]},"single_use":"boolean"},"optional":{"created_by":{"ref":258}}},
    {"object":{"email":"string","name":"string"}},
    {"object":{"import_job":{"ref":256},"token":"string","created_at":"string","expires_at":"string","id":"string","scope":{"oneOf":[{"literal":"keywords"},{"literal":"full"}]},"single_use":"boolean"},"optional":{"created_by":{"ref":258}}},
    {"object":{"id":"string","revoked_at":"string"}},
    {"object":{"app_version":"string","latest_migration":{"oneOf":["null","string"]},"schema_versions_supported":{"array":"number"}}},
    {"object":{"counts":{"ref":263},"job_id":"string","state":{"literal":"done"}}},
    {"object":{}},
    {"object":{"chunk_limits":{"ref":265},"session_id":"string","state":{"literal":"receiving"}}},
    {"object":{"max_body_bytes":"number","max_history_rows":"number","max_keywords":"number"}},
    {"object":{"chunk_count":"number","chunks_received":"number","state":{"literal":"receiving"}}},
    {"object":{"data":{"array":{"ref":268}},"meta":{"ref":68}}},
    {"object":{"id":"string","paused_at":{"oneOf":["null","string"]},"archived_at":{"oneOf":["null","string"]},"created_at":"string","updated_at":"string","name":"string"},"optional":{"paused":"boolean","description":{"oneOf":["null","string"]}}},
    {"object":{"data":{"ref":268}},"optional":{"meta":{"ref":54}}},
    {"object":{"data":{"array":{"ref":271}},"meta":{"ref":68}}},
    {"object":{"id":"string","topic_id":{"oneOf":["null","string"]},"label":{"oneOf":["null","string"]},"archived_at":{"oneOf":["null","string"]},"paused_at":{"oneOf":["null","string"]},"created_at":"string","updated_at":"string","revisions":{"array":{"ref":272}}}},
    {"object":{"id":"string","category":{"oneOf":[{"literal":"neutral"},{"literal":"comparative"},{"literal":"branded"}]},"ordinal":"number","text":"string","text_hash":"string","created_at":"string"},"optional":{"generation_reference":{"ref":273},"provider_dataset_reference":{"ref":274}}},
    {"object":{"generation_id":"string","draft_id":"string"}},
    {"object":{"report_id":"string","row_index":"number"}},
    {"object":{"data":{"ref":271}},"optional":{"meta":{"ref":54}}},
    {"object":{"data":{"array":{"ref":277}},"meta":{"ref":68}}},
    {"object":{"configuration":{"ref":278},"id":"string","archived_at":{"oneOf":["null","string"]},"created_at":"string","updated_at":"string","name":"string","cron":"string","timezone":"string"},"optional":{"enabled":"boolean","next_run_at":{"oneOf":["null","string"]}}},
    {"object":{"prompt_ids":{"array":"string"},"configurations":{"array":{"ref":279}}}},
    {"object":{"provider":{"literal":"dataforseo"},"endpoint":"string","engine":{"oneOf":[{"literal":"chat_gpt"},{"literal":"google"},{"literal":"gemini"},{"literal":"claude"},{"literal":"perplexity"}]},"source":{"oneOf":[{"literal":"consumer_scrape"},{"literal":"model_api"},{"literal":"google_aio"}]},"model":{"oneOf":["null","string"]},"parameters":{"ref":280}}},
    {"object":{}},
    {"object":{"data":{"ref":277}},"optional":{"meta":{"ref":54}}},
    {"object":{"data":{"ref":283}},"optional":{"meta":{"ref":54}}},
    {"object":{"configurations":{"array":{"ref":279}},"credential_connection_id":"string","credential_version":"string","budget_revision":"string","consent_revision":"string","estimated_cost_cents":"number"}},
    {"object":{"data":{"ref":285}},"optional":{"meta":{"ref":54}}},
    {"object":{"id":"string","state":{"oneOf":[{"literal":"completed"},{"literal":"failed"},{"literal":"running"},{"literal":"skipped"},{"literal":"partial"},{"literal":"planned"},{"literal":"blocked"},{"literal":"cancelled"}]},"created_at":"string","updated_at":"string","finished_at":{"oneOf":["null","string"]},"planned_at":{"oneOf":["null","string"]},"sample_count":{"oneOf":["null","number"]}}},
    {"object":{"data":{"array":{"ref":285}},"meta":{"ref":68}}},
    {"object":{"data":{"array":{"ref":288}},"meta":{"ref":68}}},
    {"object":{"id":"string","measurement":{"oneOf":[{"literal":"unknown"},{"literal":"failed"},{"literal":"partial"},{"literal":"answer_present"},{"literal":"aio_not_present"},{"literal":"unavailable"}]},"source":{"oneOf":[{"literal":"consumer_scrape"},{"literal":"model_api"},{"literal":"google_aio"}]},"engine":{"oneOf":[{"literal":"chat_gpt"},{"literal":"google"},{"literal":"gemini"},{"literal":"claude"},{"literal":"perplexity"}]},"prompt":"string","prompt_revision_id":"string","evidence":{"oneOf":["null",{"ref":289}]},"citations":{"array":{"ref":291}},"cost_usd":{"oneOf":["null","string"]},"cost_state":{"oneOf":[{"literal":"derived"},{"literal":"unknown"},{"literal":"pending"},{"literal":"confirmed"},{"literal":"refund_pending"}]}}},
    {"object":{"answer_text":{"oneOf":["null","string"]},"raw":"unknown","answer_truncated":"boolean","raw_truncated":"boolean","search_results":{"array":{"ref":290}},"requested_locale":{"oneOf":["null","string"]},"effective_locale":{"oneOf":["null","string"]},"locale_mechanism":{"oneOf":["null","string"]},"requested_model":{"oneOf":["null","string"]},"actual_model":{"oneOf":["null","string"]},"provider_status":{"oneOf":["null","string"]},"observed_at":{"oneOf":["null","string"]},"fetched_at":"string","recorded_source":{"oneOf":[{"literal":"fresh"},{"literal":"cache"}]}}},
    {"object":{"url":"string","title":{"oneOf":["null","string"]},"position":"number"}},
    {"object":{"url":"string","title":{"oneOf":["null","string"]},"position":"number"}},
    {"object":{"data":{"ref":293}},"optional":{"meta":{"ref":54}}},
    {"object":{"comparable":"boolean","reason":{"oneOf":["null","string"]},"current_run_id":"string","current":{"ref":294},"delta":{"oneOf":["null","number"]},"baseline":{"literal":"neutral"},"category":{"literal":"neutral"},"strata":{"array":{"ref":295}},"next_cursor":{"oneOf":["null","string"]}},"optional":{"previous_run_id":"string","previous":{"ref":294},"previous_next_cursor":{"oneOf":["null","string"]}}},
    {"object":{"expected":"number","observed":"number","eligible":"number","mentioned":"number","absent_aio":"number","partial":"number","failed":"number","unknown":"number","missing":"number","coverage":"number","mention_rate":{"oneOf":["null","number"]}}},
    {"object":{"category":{"oneOf":[{"literal":"unknown"},{"literal":"neutral"},{"literal":"comparative"},{"literal":"branded"}]},"current":{"ref":294},"comparable":"boolean","reason":{"oneOf":["null","string"]},"delta":{"oneOf":["null","number"]}},"optional":{"previous":{"ref":294}}},
    {"object":{"data":{"ref":297}},"optional":{"meta":{"ref":54}}},
    {"object":{"items":{"array":{"ref":288}},"run_id":"string","next_cursor":{"oneOf":["null","string"]}},"optional":{"scope":{"ref":298}}},
    {"object":{"complete":"boolean","max_pages":"number","loaded":"number","resumed":"boolean"}},
    {"object":{"data":{"ref":300}},"optional":{"meta":{"ref":54}}},
    {"object":{"drafts":{"array":{"ref":304}},"method":{"oneOf":[{"literal":"context_template_heuristic"},{"literal":"manual_fallback"}]},"context_updated_at":{"oneOf":["null","string"]},"requires_acceptance":"boolean","cost_usd":"string","limitations":{"array":"string"}},"optional":{"input_snapshot":{"ref":301}}},
    {"object":{"context":{"ref":302},"competitors":{"array":{"ref":303}}}},
    {"object":{"business":"string","audience":"string","products":"string","goals":"string","agent_rules":"string"}},
    {"object":{"id":"string","label":{"oneOf":["null","string"]},"domain":"string"}},
    {"object":{"text":"string","category":{"oneOf":[{"literal":"neutral"},{"literal":"comparative"},{"literal":"branded"}]},"provenance":{"oneOf":[{"literal":"generated_hypothesis"},{"literal":"provider_dataset"},{"literal":"model_generated_hypothesis"}]},"evidence_ids":{"array":"string"},"popularity":{"oneOf":["null","number"]},"accepted":{"literal":false}},"optional":{"generation_reference":{"ref":273},"provider_dataset_reference":{"ref":274}}},
    {"object":{"data":{"ref":306}},"optional":{"meta":{"ref":54}}},
    {"object":{"prompts":{"array":{"ref":271}}}},
    {"object":{"data":{"ref":308}},"optional":{"meta":{"ref":54}}},
    {"object":{"version":{"literal":1},"snapshot_hash":"string","estimated_cost_cents":"number","estimate_kind":{"literal":"forecast"},"is_guaranteed_maximum":{"literal":false},"credential_connection_id":"string","credential_version":"string","budget_revision":"string","consent_revision":"string","expires_at":"string","limitations":{"array":"string"},"configuration":{"ref":309},"input_snapshot":{"ref":301}}},
    {"object":{"provider":{"literal":"dataforseo"},"engine":{"literal":"chat_gpt"},"model":"string","language_code":"string","max_output_tokens":"number","advisory_cost_limit_cents":"number"},"optional":{"country_iso_code":"string"}},
    {"object":{"data":{"ref":311}},"optional":{"meta":{"ref":54}}},
    {"object":{"generation_id":"string","drafts":{"array":{"ref":312}},"cost_usd":{"oneOf":["null","string"]},"cost_state":{"oneOf":[{"literal":"unknown"},{"literal":"confirmed"}]},"method":{"literal":"model_generated_hypothesis"},"limitations":{"array":"string"}}},
    {"object":{"draft_id":"string","text":"string","category":{"oneOf":[{"literal":"neutral"},{"literal":"comparative"},{"literal":"branded"}]},"provenance":{"literal":"model_generated_hypothesis"},"evidence_ids":{"emptyArray":true},"popularity":"null","accepted":{"literal":false}}}
  ]
};
